Gemfile, Gemfile.lock, app/models/ability.rb, app/views/dashboard/_index_partials/_heading_actions.html.erb, app/views/homepage/_home_header.html.erb, spec/support/capybara.rb, spec/support/devise.rb, spec/views/dashboard/_index_partials/_heading_actions.html.erb_spec.rb, spec/views/homepage/_home_header.html.erb_spec.rb
=> Restrict Ingest to Administrators

config/locales/blacklight.en.yml
=> Change page title.

app/controllers/catalog_controller.rb
=> Disable tag cloud.

README.md
cp config.example.yml config.yml necessary for setup.
=> Adds necessary step to readme setup

config/initializers/sufia.rb
=> configure contact form

app/views/static/agreement.html.erb
Fixes #40. This simply gets all the text in place according to issue #40, however, layout could potentially use some work. We can decide on what to do with the layout of the text on that page anytime.
=> Replaces content of deposit agreement with custom OSU agreement

config/initializers/redis_config.rb, lib/tasks/resque.rake
Fixed by https://github.com/ClevelandArtGIT/cma-archives/commit/177751083753bab18aa94ed2918f9463e6c6e1f6#diff-47dbc8225025d7a1c65fb7f3fba5ee7eR14 and related by @mjgiarlo.
=> There were bugs causing Resque to not fire.

app/assets/stylesheets/text_color.css, app/views/_footer.html.erb, config/locales/en.yml
Fixes #48 Overrides the footer partial just in case more needs to be added to the footer overtime.
=> Override footer to add custom info

app/assets/stylesheets/application.css, app/assets/stylesheets/word-wrap.css.scss
=> Fixed profile email spilling over

app/models/user.rb, config/initializers/devise.rb, spec/routing/user_profile_routing_spec.rb
=> updated devise to authenticate on username

app/assets/stylesheets/osu.scss
=> updated color on hover over links in footer

config/locales/en.yml, spec/views/homepage/_home_header.html.erb_spec.rb
=> updated browse button text

circle.yml
=> Should fix the Circle Java error

Gemfile, Gemfile.lock, app/assets/stylesheets/sufia.scss
Upgrade to sufia and kaminari. Kaminari needed a specific branch by jcoyne and with the upgrade to sufia, there was a new stylesheet that needed importing as well.
=> Updates to sufia and kaminari

app/inputs/uri_multi_value_input.rb, app/schemas/scholars_archive_schema.rb, config/locales/sufia.en.yml
Fixes #135 Fixes #140 Fixes #137 Fixes #81 Fixes #84
=> Adds proper human readable names/descriptions to ingest form and item record page

app/views/records/edit_fields/_rights.html.erb
=> Only show the option to select one license.

Gemfile.lock, app/models/ability.rb, config/initializers/sufia.rb
Fixes #141. Updated sufia and activated the citation link.
=> Updated sufia and activated citations.

app/controllers/catalog_controller.rb, app/forms/file_edit_form.rb, app/models/generic_file.rb, app/models/solr_document.rb, app/presenters/file_presenter.rb, app/views/records/show_fields/_nested_authors.html.erb, app/views/shared/_attributes.html.erb, config/locales/sufia.en.yml, spec/models/generic_file_spec.rb, spec/views/records/show_fields/_nested_authors.html.erb_spec.rb, spec/views/shared/_attributes.html.erb_spec.rb
=> Index and display nested authors.

config/locales/sufia.en.yml
=> Added search box terms to locale, changed to SA@OSU

app/assets/stylesheets/osu.scss, config/locales/sufia.en.yml
=> Lined up fields on ingest form and added keyword flavortext

app/assets/javascripts/jquery.flot.axislabels.js, app/views/generic_files/_flot_stats.js.erb
=> replace axis label plugin flot

app/views/batch/_metadata.html.erb, app/views/batch/_more_metadata.html.erb
=> issue#203: Move up author field

app/views/generic_files/_flot_stats.js.erb
=> updated style on the 'last three months button

app/controllers/generic_files_controller.rb
=> added custom headers in daily/monthly csv export files

app/assets/stylesheets/osu.scss
=> issue#256: solve search bar spill over page boundaries

lib/scholars_archive/uri_enabled_string_field.rb
=> use preferred_label if possible for uri

lib/scholars_archive/uri_enabled_string_field.rb
Reverts osulp/Scholars-Archive#266
=> Revert "use preferred_label if possible for uri"

app/assets/javascripts/add_date_field.js.coffee, app/assets/stylesheets/sufia.scss, app/forms/file_edit_form.rb, app/views/records/edit_fields/_date_created.html.erb, app/views/records/edit_fields/_default.html.erb, config/locales/sufia.en.yml, spec/features/edit_batch_spec.rb, spec/forms/file_edit_form_spec.rb, spec/views/records/edit_fields/_default.html.erb_spec.rb
Fixes #280 and cleans up some aspects of the style and UI related to date fields on the ingest form
=> fixes Year Published, and some of the related form UI

app/forms/file_edit_form.rb, app/helpers/sufia_helper.rb, app/jobs/scholars_archive/batch_update_job.rb, app/views/records/show_fields/_rights.html.erb, app/views/records/show_fields/_tag.html.erb
Fixes #290 Fixes #292 Fixes #293
=> Fixes Keywords not showing up and authors not saving

Gemfile, Gemfile.lock, app/controllers/downloads_controller.rb, config/jetty.yml, config/settings.local.yml
fixes jetty configs causing local development breakage
fixes #118 fixes #274 fixes #275
=> adds server side Google analytics for direct downloads

app/controllers/downloads_controller.rb
=> sets event, action, and label to work how Sufia stats analytics

app/mailers/embargoes_mailer.rb, app/views/embargoes_mailer/embargoes_lifted_email.html.erb, config/application.rb, config/config.example.yml, config/environments/development.rb, config/jetty.yml, config/settings.local.yml, lib/tasks/process_embargoes.rake, spec/mailers/embargoes_mailer_spec.rb
=> adds ActionMailer and views related to embargo lifting cron..etc

config/application.rb, config/config.example.yml
=> loads ERB from config/config.yml, updates example config

lib/tasks/process_embargoes.rake
=> enables multiple email addresses for embargoes lifting status

app/views/generic_files/_permission_form.html.erb
=> adds missing data-index in partial for proper form POST to remove perms

app/views/records/show_fields/_rights.html.erb, app/views/records/show_fields/_tag.html.erb
Fixes #305 Fixes #306 I looked into what itemtype is but didn't quite understand. Can someone shed some light on why you would want to use an itemtype?
=> Fix itemtype for tag and rights

app/controllers/application_controller.rb, app/controllers/generic_files_controller.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/views/user_mailer/shared_access_to.html.erb, app/views/user_mailer/support_invalid_user.html.erb, app/views/users/_edit_primary.html.erb, spec/controllers/application_controller_spec.rb, spec/features/edit_batch_spec.rb, spec/features/edit_file_spec.rb, spec/features/edit_help_spec.rb, spec/jobs/batch_update_job_spec.rb, spec/mailers/user_mailer_spec.rb, spec/models/user_spec.rb, spec/views/batch/edit.html.erb_spec.rb, spec/views/homepage/_home_header.html.erb_spec.rb
Prepares plumbing for user notifications, established user email related validations.
fixes #316 
fixes #244
=> Fix/share with notification, user email validations/handling/notification

config/routes.rb
Reconfigured our staging server to use the 'staging' environment and verified that this fixes #340
=> fixes 404s on production and staging per github project Sufia issue #1928

config/database.yml
=> use the ENV variables for the database connection

Gemfile, Gemfile.lock, app/models/user.rb, config/application.rb, config/initializers/devise.rb, config/routes.rb, db/migrate/20160427212251_add_username_to_user.rb, db/migrate/20160427212320_user_roles.rb, db/schema.rb
=> added rubycas client and config options

.fcrepo_wrapper, .solr_wrapper, Gemfile, Gemfile.lock, app/models/user.rb, config/application.rb, config/initializers/devise.rb, config/routes.rb, db/migrate/20160718201239_user_roles.rb, db/migrate/20160718201439_add_username_to_user.rb, db/schema.rb
=> integrates CAS login, includes default fcrepo_wrapper and solr_wrapper

Gemfile, Gemfile.lock, circle.yml, config/application.rb, config/initializers/config.rb, config/initializers/triplestore_adapter.rb, config/settings.yml, config/settings/development.yml, config/settings/production.yml, config/settings/staging.yml, config/settings/test.yml, config/triplestore_adapter/blazegraph/blazegraph.properties, config/triplestore_adapter/blazegraph/log4j.properties, spec/rails_helper.rb, spec/support/triplestore_adapter.rb, spec/triplestore/triplestore_adapter_spec.rb
=> integrates triplestore_adapter as the backend RDF cache, introduces tests, configuration, and circleci

README.md, config/initializers/triplestore_adapter.rb, lib/tasks/scholars_archive.rake
=> updates README and introduces some fixes for testing environment

lib/tasks/scholars_archive.rake
=> sets RAILS_ENV when executing rake tasks

Gemfile, Gemfile.lock, app/assets/javascripts/add_date_field.js.coffee, app/assets/javascripts/application.js, app/assets/javascripts/hydra-editor/manage_repeating_fields.js, app/assets/javascripts/nested_fields.js.coffee, app/controllers/catalog_controller.rb, app/forms/curation_concerns/generic_work_form.rb, app/models/generic_work.rb, app/models/solr_document.rb, app/presenters/sufia/work_show_presenter.rb, app/views/curation_concerns/base/_attribute_rows.html.erb, app/views/records/edit_fields/_date_created.html.erb, circle.yml, spec/features/date_selector_spec.rb, spec/rails_helper.rb, spec/support/webmock.rb
=> Adds date dropdown and js associated

app/controllers/curation_concerns/generic_works_controller.rb
=> Adds default value to new form

config/initializers/legato.rb
=> adds Legato initialization to ensure development, staging, and testing environments have analytics

app/assets/javascripts/application.js, app/assets/javascripts/sufia/flot_stats.js, app/assets/stylesheets/osu.scss, app/views/stats/_page_view_table.html.erb, app/views/stats/file.html.erb, app/views/stats/work.html.erb
added style css and js changes for pr #424
=> added stats item level osu style and js

config/routes.rb, solr/config/solrconfig.xml
=> add config to enable admin stats

app/assets/javascripts/application.js, app/assets/javascripts/sufia/featured_works.js, app/models/ability.rb, app/models/user.rb, app/presenters/scholars_archive/work_show_presenter.rb
This adds role management to Scholars archive and returns the functionality of being able to feature and unfeature an item from the item record page. Fixes #377
=> Adds roles and toggle feature/unfeature

app/views/_user_util_links.html.erb, config/routes.rb
fixes #467 
changes sidekiq address to something more generic for if/when sidekiq is replaced
=> configured sidekiq server, and deploy cleanup

app/views/_user_util_links.html.erb
=> renders proper link path to queues-monitor

.gitignore, app/actors/hyrax/actors/etd_actor.rb, app/controllers/hyrax/etds_controller.rb, app/forms/hyrax/default_work_form.rb, app/forms/hyrax/etd_form.rb, app/models/concerns/scholars_archive/default_metadata.rb, app/models/default_work.rb, app/models/etd.rb, app/views/hyrax/etds/_etd.html.erb, config/initializers/hyrax.rb, config/locales/etd.en.yml, config/locales/etd.es.yml, spec/actors/hyrax/actors/etd_actor_spec.rb, spec/controllers/hyrax/etds_controller_spec.rb, spec/features/create_etd_spec.rb, spec/forms/hyrax/etd_form_spec.rb, spec/models/etd_spec.rb
This branch is for DSpace migration and should be merged to Hyrax
=> Add default metadata as module; and two work types: default_work, etd

app/models/concerns/scholars_archive/default_metadata.rb
reorders the fields (alphabetical) and then adds the date_uploaded per our Hyrax Work Types document
=> [WIP] adds field for uploaded date

Gemfile, Gemfile.lock, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/initializers/hyrax.rb, config/initializers/sidekiq.rb, config/local_env.example.yml, config/redis.yml, config/routes.rb, config/sidekiq.yml
=> adds sidekiq and redis for background jobs on production and staging

config/initializers/mini_magick.rb
=> adds configuration for server side derivative generation bugfix

config/deploy.rb
=> links to analytics.yml on the server side

app/views/records/edit_fields/_subject.html.erb, db/schema.rb
=> Changes url for autocomplete questioning authority

app/views/hyrax/stats/file.html.erb
=> Display filename on the file stats page

config/application.rb
=> Updates config to load lib classes

app/models/concerns/scholars_archive/default_metadata.rb
=> Adds the replaces metadata to the default metadata

app/controllers/hyrax/etds_controller.rb, app/forms/hyrax/default_work_form.rb, app/forms/hyrax/etd_form.rb, app/models/solr_document.rb, app/presenters/etd_presenter.rb, app/views/hyrax/base/_attribute_rows.html.erb, lib/tasks/handle_dump.rake
=> Adds replaces to edit form and show page. Adds rake task for mapping

config/initializers/mini_magick.rb, config/sidekiq.yml
=> adds debug for minimagick and sidekiq for troubleshooting

app/forms/hyrax/default_work_form.rb, app/forms/hyrax/etd_form.rb, app/models/concerns/scholars_archive/default_metadata.rb, app/views/hyrax/base/_attribute_rows.html.erb
Adds the metadata to the proper places in the form Per the MAP file. Also adds the first steps to add the metadata to the show page.
=> Adds all terms to both ETD and Default forms

config/authorities/resource_types.yml
=> updates resource types to match the MAP spreadsheet

.circleci/config.yml, app/views/hyrax/base/_work_description.erb, config/locales/hyrax.en.yml, spec/views/hyrax/base/_work_description.erb_spec.rb
Added citeable url for the current work in the show page.
fixes #520 
Screenshot:
=> added work url in the show page

config/locales/simple_form.en.yml, db/schema.rb
=> Adds in rest of descriptions.

app/forms/hyrax/undergraduate_thesis_or_project_form.rb, spec/forms/hyrax/undergraduate_thesis_or_project_form_spec.rb
=> Updated undergrad thesis to not require degree info

app/services/scholars_archive/degree_level_service.rb, app/services/scholars_archive/degree_name_service.rb, app/views/records/edit_fields/_degree_level.html.erb, app/views/records/edit_fields/_degree_name.html.erb, config/authorities/degree_level.yml, config/authorities/degree_name.yml, spec/services/scholars_archive/degree_level_service_spec.rb, spec/services/scholars_archive/degree_name_service_spec.rb
fixes #543 
Degree Level dropdown:
Degree Name dropdown:
=> added degree level and degree name services

app/forms/hyrax/default_work_form.rb, app/views/scholars_archive/base/_form_geo.html.erb
=> moved location field into the Geographic related section in the forms

app/models/concerns/scholars_archive/default_metadata.rb, app/views/scholars_archive/base/_form_dates.html.erb, spec/views/scholars_archive/base/_form_dates.erb_spec.rb
=> updated form dates to render multiple fields when available

app/forms/hyrax/default_work_form.rb, config/initializers/base_actor_hack.rb
=> adds a hack during migration to allow setting date_uploaded and date_modified

app/services/scholars_archive/label_parser_service.rb, spec/services/scholars_archive/label_parser_service_spec.rb
=> fixes LabelParserService bug

config/initializers/base_actor_hack.rb
enables hack to work alongside regular form usage
=> bugfix for hack to work alongside normal functionality

app/controllers/catalog_controller.rb, app/helpers/hyrax_helper.rb
=> display only the label in the facets list on the main search page

app/controllers/catalog_controller.rb, app/helpers/hyrax_helper.rb
Screenshot: Showing only the first 150 words from abstract
closes #669
=> updated catalog controller to adjust the search results view

config/initializers/hyrax.rb
fixes #341 
Changes have to be made to the servers linked files as well
=> updates contact form details

app/models/concerns/scholars_archive/article_metadata.rb, app/models/concerns/scholars_archive/default_metadata.rb, app/models/concerns/scholars_archive/etd_metadata.rb, app/models/concerns/scholars_archive/oer_metadata.rb, app/models/nested_geo.rb
Changed URI definitions to use rdf-vocab where possible.
Added links to MAP in each file.
Removed old comments.
Changed bibo peerReviewed back to URI
=> Changed URIs to rdf-vocab, cleaned up comments.

app/models/user.rb, spec/models/user_spec.rb
=> added mailboxer_email method for messaging

config/workflows/datasets.json, config/workflows/gtd.json, config/workflows/one_step.json, config/workflows/stakeholder.json
=> Adds revoking and granting edit to depositor upon transition

config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/environments/test.rb
=> updated config environments to set action_mailer options

config/initializers/mailboxer.rb
=> updated default_from in mailboxer initializer

app/actors/hyrax/actors/honors_college_thesis_actor.rb, app/controllers/hyrax/honors_college_theses_controller.rb, app/forms/hyrax/honors_college_thesis_form.rb, app/models/honors_college_thesis.rb, app/presenters/honors_college_thesis_presenter.rb, app/views/hyrax/honors_college_theses/_honors_college_thesis.html.erb, config/initializers/hyrax.rb, config/locales/honors_college_thesis.de.yml, config/locales/honors_college_thesis.en.yml, config/locales/honors_college_thesis.es.yml, config/locales/honors_college_thesis.fr.yml, config/locales/honors_college_thesis.it.yml, config/locales/honors_college_thesis.pt-BR.yml, config/locales/honors_college_thesis.zh.yml, spec/actors/hyrax/actors/honors_college_thesis_actor_spec.rb, spec/controllers/hyrax/honors_college_theses_controller_spec.rb, spec/features/create_honors_college_thesis_spec.rb, spec/forms/hyrax/honors_college_thesis_form_spec.rb, spec/models/honors_college_thesis_spec.rb, spec/presenters/hyrax/honors_college_thesis_presenter_spec.rb
Fixes #672 Just need to add admin set on prod server.
=> Adds honors college model

app/actors/scholars_archive/actors/add_other_field_option_actor.rb, spec/actors/scholars_archive/actors/add_other_field_option_actor_spec.rb
=> updated create method on AddOtherFieldOptionActor

config/locales/hyrax.en.yml
=> Changes search placeholder

app/services/scholars_archive/license_service.rb, app/views/records/edit_fields/_license.html.erb
=> Removes CC0 from GTD and Undergrad

app/views/hyrax/base/_form_visibility_component.html.erb
=> Sets default embargo to OSU for ETDs

app/actors/scholars_archive/actors/add_other_field_option_actor.rb, spec/actors/scholars_archive/actors/add_other_field_option_actor_spec.rb
=> implemented validate function for add_other_field_option actor

app/assets/javascripts/hyrax/flot_stats.js
=> Add Blacklight onload to flot.js

app/assets/stylesheets/osu.scss, app/views/scholars_archive/base/_form_geo.html.erb
=> Fixes form width and Location styling

app/models/administrative_report_or_publication.rb, app/models/article.rb, app/models/concerns/scholars_archive/excluded_article_licenses.rb, app/models/concerns/scholars_archive/excluded_default_licenses.rb, app/models/concerns/scholars_archive/excluded_etd_licenses.rb, app/models/concerns/scholars_archive/excluded_oer_licenses.rb, app/models/conference_proceedings_or_journal.rb, app/models/dataset.rb, app/models/default.rb, app/models/eesc_publication.rb, app/models/graduate_project.rb, app/models/graduate_thesis_or_dissertation.rb, app/models/honors_college_thesis.rb, app/models/open_educational_resource.rb, app/models/technical_report.rb, app/models/undergraduate_thesis_or_project.rb, app/services/scholars_archive/license_service.rb
=> Refactor excluded licenses into behaviors

app/services/scholars_archive/triple_powered_service.rb
=> update triple powered service to try fetching remote

config/authorities/licenses.yml
=> Adds CC4.0 Licenses

config/environments/development.rb, config/initializers/loc_generic_authority_hack.rb
fixes #794
fixes #778 
**With wildcard**
**Current without the wildcard**
=> adds local QA hack, fixes development caching

app/assets/stylesheets/osu.scss, app/views/shared/_select_work_type_modal.html.erb
=> Fixes Work select modal to align and be 2 columns

app/services/scholars_archive/admin_set_select_service.rb, app/views/hyrax/base/_form_relationships.html.erb, app/views/hyrax/base/_guts4form.html.erb, spec/services/scholars_archive/admin_set_select_service_spec.rb
Fixes #797 
Fixes #798
Fixes #799
=> Fixes Default admin set issue and hidden form elements

app/forms/hyrax/default_form.rb, app/services/scholars_archive/form_metadata_service.rb, app/views/records/edit_fields/_license.html.erb
=> Changes license to 'single-value' same way rights-statements are

app/views/hyrax/base/_attribute_rows.html.erb, app/views/scholars_archive/base/_form_geo.html.erb, config/locales/simple_form.en.yml
=> Move Hydroligic Unit Code and fix license label label

app/assets/stylesheets/osu.scss
=> Fixes form length.

app/views/records/edit_fields/_default.html.erb, app/views/records/edit_fields/_file_format.html.erb, app/views/records/edit_fields/_keyword.html.erb
=> Removes file_format and keyword from form unless admin

app/assets/javascripts/add_date_field.js.coffee, app/helpers/application_helper.rb, app/inputs/multi_value_date_input.rb, app/views/records/edit_fields/_date_collected.html.erb, app/views/scholars_archive/base/_form_dates.html.erb, spec/inputs/multi_value_date_input_spec.rb, spec/views/scholars_archive/base/_form_dates.erb_spec.rb
fixes #788 
fixes #681 
fixes #786 
fixes #785
=> added calendar widget to date collected

config/routes.rb
=> Removes deprecated code

app/controllers/catalog_controller.rb
=> Uses date uploaded and date created for sortable fields

app/forms/hyrax/dataset_form.rb, app/forms/scholars_archive/dataset_form_behavior.rb, spec/forms/hyrax/dataset_form_spec.rb
fixes #779 
WARNING! @vantuyls did this and he doesn't know what he's doing. Proceed with caution.
=> Reordering formmms

app/indexers/default_work_indexer.rb, app/models/concerns/scholars_archive/has_triple_powered_properties.rb, app/services/scholars_archive/triple_powered_service.rb, lib/scholars_archive/triple_powered_properties/has_url_validator.rb, lib/scholars_archive/triple_powered_properties/triple_powered_form.rb, spec/actors/scholars_archive/actors/add_other_field_option_actor_spec.rb, spec/scholars_archive/triple_powered_properties/triple_powered_form_spec.rb, spec/services/scholars_archive/triple_powered_service_spec.rb
updated `ScholarsArchive::TriplePoweredService.fetch_all_labels` to append `RDF::Vocab::DC.date` info to fetched labels when available 
fixes #706
=> updated triple_powered_service to query rdf dc date

app/controllers/catalog_controller.rb
=> enabled graduation_year to facet with blacklight range limit widget

app/services/scholars_archive/workflow/deposited_notification.rb
=> updated deposited_notification to include a citeable url in the email

app/assets/javascripts/application.js, app/assets/javascripts/embargo_date_field.js, app/controllers/concerns/scholars_archive/works_controller_behavior.rb, app/forms/scholars_archive/default_work_form_behavior.rb, app/models/concerns/scholars_archive/default_metadata.rb, app/models/solr_document.rb, app/presenters/concerns/scholars_archive/default_presenter_behavior.rb, app/views/hyrax/base/_attribute_rows.html.erb, app/views/hyrax/base/_form_permission_embargo.html.erb, app/views/hyrax/base/_form_visibility_component.html.erb, spec/actors/scholars_archive/actors/add_other_field_option_actor_spec.rb
=> Initial work on date picker and embargo reason.

app/forms/hyrax/forms/batch_edit_form.rb, app/forms/hyrax/forms/batch_upload_form.rb, app/models/batch_upload_item.rb, app/views/hyrax/base/_form.html.erb, app/views/scholars_archive/base/_form_geo.html.erb, config/admin_set_map.yml, config/initializers/hydra_config.rb, config/initializers/hyrax.rb, spec/views/scholars_archive/base/_form_geo.erb_spec.rb
=> added batch_upload_item to include SA default metadata

app/assets/javascripts/embargo_reason_field.js, app/views/hyrax/base/_form_visibility_component.html.erb
Adds in text field for "Other embargo reason"
=> Adds other embargo reason.

app/assets/javascripts/embargo_date_field.js, app/assets/javascripts/embargo_reason_field.js, app/views/hyrax/base/_form_permission_embargo.html.erb
=> Embargo changes on edit

app/actors/scholars_archive/actors/nested_fields_operations_actor.rb, app/controllers/concerns/scholars_archive/works_controller_behavior.rb, app/forms/scholars_archive/dataset_form_behavior.rb, app/forms/scholars_archive/default_work_form_behavior.rb, app/views/scholars_archive/base/_form_geo.html.erb, config/application.rb, spec/actors/scholars_archive/actors/nested_fields_operations_actor_spec.rb
- moved set_geo method from controller behavior to new a actor so that it is also available in batch uploads
references #790
=> added nested fields actor to set geo attributes

app/actors/scholars_archive/actors/add_other_field_option_actor.rb, app/assets/javascripts/degree_other.js.coffee, app/controllers/concerns/scholars_archive/works_controller_behavior.rb, app/forms/scholars_archive/etd_work_form_behavior.rb, app/models/concerns/scholars_archive/etd_metadata.rb, app/services/scholars_archive/degree_name_service.rb, app/views/records/edit_fields/_degree_name.html.erb, config/authorities/degree_name.yml, config/locales/simple_form.en.yml, config/locales/simple_form.es.yml, spec/actors/scholars_archive/actors/add_other_field_option_actor_spec.rb, spec/views/records/edit_fields/_degree_field.html.erb_spec.rb, spec/views/records/edit_fields/_degree_level.html.erb_spec.rb, spec/views/records/edit_fields/_degree_name.html.erb_spec.rb
=> added degree_name local authority

config/authorities/degree_level.yml, spec/services/scholars_archive/degree_level_service_spec.rb
=> removed post-doctoral from degree level

app/controllers/catalog_controller.rb, app/indexers/default_work_indexer.rb, app/models/concerns/scholars_archive/has_etd_triple_powered_properties.rb, app/models/graduate_project.rb, app/models/graduate_thesis_or_dissertation.rb, app/models/honors_college_thesis.rb, app/models/solr_document.rb, app/models/undergraduate_thesis_or_project.rb, app/presenters/concerns/scholars_archive/etd_presenter_behavior.rb, app/views/hyrax/base/_attribute_rows.html.erb, lib/scholars_archive/triple_powered_properties/has_url_validator.rb
=> updated triple powered properties to support single value fields

config/authorities/degree_name.yml
=> adds HBFA to degree name

app/assets/stylesheets/osu.scss, app/assets/stylesheets/osu_settings.scss
=> added footer css to match OSU branding

app/assets/javascripts/embargo_date_field.js, app/assets/stylesheets/osu.scss, app/views/hyrax/base/_form_visibility_component.html.erb, config/locales/simple_form.en.yml
=> Alters css for embargoes

config/authorities/degree_name.yml
=> updated degree_name authority list from Master Degree Name List spreadsheet

app/views/hyrax/base/_form_visibility_component.html.erb, config/locales/hyrax.en.yml, config/locales/simple_form.en.yml
fixes #860 
fixes #872 
fixes #861
=> updated form visibility component

app/views/hyrax/dashboard/_index_partials/_proxy_rights.html.erb, config/locales/hyrax.en.yml
=> added heading and description in proxy rights section under user profile

app/controllers/catalog_controller.rb, app/models/concerns/scholars_archive/has_etd_triple_powered_properties.rb, app/models/solr_document.rb, app/presenters/concerns/scholars_archive/etd_presenter_behavior.rb, app/views/hyrax/base/_attribute_rows.html.erb, spec/models/solr_document_spec.rb
=> added degree grantors label to index and show page

app/services/scholars_archive/triple_powered_service.rb
=> send error to rails logger on triple_powered_service fetch_from_store

app/views/mailboxer/message_mailer/new_message_email.html.erb, config/locales/hyrax.en.yml
=> updated mailboxer new message email and subject

app/models/concerns/scholars_archive/has_solr_labels.rb
=> updated has_solr_labels to parse valid NestedRelatedItems only

app/models/concerns/scholars_archive/date_operations.rb
updated clean_datetime to send warning to logs when input date is invalid
=> update date_operations to handle invalid values on to_solr 

app/models/concerns/scholars_archive/has_solr_labels.rb
=> updated has_solr_labels to handle invalid values for NestedGeo

app/jobs/reindex_everything_job.rb, lib/tasks/reindex_everything.rake
added rake task to run ReindexEverythingJob and reindex from SOLR
references #867
=> added scholars_archive reindex_everything_job

app/jobs/application_job.rb, app/jobs/reindex_everything_job.rb, app/jobs/scholars_archive/application_job.rb, config/application.rb, config/environments/test.rb
=> enabled sidekiq for sa application jobs

app/views/hyrax/stats/work.html.erb
=> added text for all work analytics pages

app/services/scholars_archive/academic_units_service.rb, app/services/scholars_archive/edtf_date_compare_service.rb, app/views/records/edit_fields/_academic_affiliation.html.erb, spec/services/scholars_archive/edtf_date_compare_service_spec.rb, spec/views/records/edit_fields/_academic_affiliation.html.erb_spec.rb
=> filter academic units options to display only open units

config/locales/simple_form.en.yml
=> updated contributor_advisor label for honors_college_thesis model

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/models/oai_set.rb, app/models/solr_document.rb, config/routes.rb, lib/scholars_archive/document/qualified_dublin_core.rb, spec/models/solr_document_spec.rb
More work on solr doc configuration, custom fields for OAI output.
Copied OAI Set model, cleaned up Set title and removed facet limit. Added tests.
Fixes #809
=> Add blacklight_oai_provider gem and run generator.

app/actors/scholars_archive/actors/add_other_field_option_actor.rb, app/actors/scholars_archive/actors/nested_fields_operations_actor.rb, app/assets/javascripts/application.js, app/assets/javascripts/field_other.js.coffee, app/assets/stylesheets/osu.scss, app/controllers/concerns/scholars_archive/works_controller_behavior.rb, app/controllers/other_options_controller.rb, app/forms/scholars_archive/default_work_form_behavior.rb, app/inputs/multi_value_select_other_input.rb, app/models/concerns/scholars_archive/default_metadata.rb, app/services/scholars_archive/other_affiliation_service.rb, app/services/scholars_archive/other_option_create_success_service.rb, app/views/other_options/destroy.js.erb, app/views/records/edit_fields/_other_affiliation.html.erb, config/application.rb, config/authorities/other_affiliation.yml, config/locales/simple_form.en.yml, config/routes.rb, lib/scholars_archive/triple_powered_properties/has_url_validator.rb, spec/actors/scholars_archive/actors/add_other_field_option_actor_spec.rb, spec/controllers/other_options_controller_spec.rb, spec/rails_helper.rb, spec/services/scholars_archive/other_option_create_success_service_spec.rb
fixes #958 
Screenshot for new form (other_affiliation):
Screenshot for edit form (other_affiliation):
Screenshot for new/edit form (validation of new "Other" entries)
=> added other affiliation local authority

app/controllers/scholars_archive/handles_controller.rb, spec/controllers/scholars_archive/handles_controller_spec.rb
=> fixes bugs with handle controller redirects

app/controllers/catalog_controller.rb, app/models/oai_set.rb, app/models/solr_document.rb
Do solr lookup for Admin Set title.
Fixes #1000
=> Change to isPartOf_ssim for OAI Admin Set.

app/models/solr_document.rb
=> added special case for Collection in oai_identifier

app/models/solr_document.rb, spec/models/solr_document_spec.rb
=> Add other_affiliation_label method and specs.

config/routes.rb
=> adds dspace routes

Gemfile, Gemfile.lock
=> Change blacklight_oai_provider to UNC Libraries fork.

config/database.yml
=> forces database connection to try reconnecting

config/environments/production.rb
updated host in prod env so that we can link the proper base url and protocol in emails
=> updated host in prod env for emails

app/assets/javascripts/application.js, app/assets/javascripts/default_datatable_order.js, app/views/hyrax/admin/workflows/index.html.erb, config/initializers/hyrax_status_list_service_hack.rb
=> added fix to correct filtering in submissions tab

config/locales/default.en.yml
changed wording for Other Content to make it more sensical for users.
addresses: https://github.com/osulp/Scholars-Archive/issues/1018
nb. review this carefully please, i'm an amateur.
=> change wording for "Other Content"

config/locales/hyrax.en.yml
=> Capitalize Resource Type facet. Override Hyrax setting.

app/controllers/catalog_controller.rb
=> Alphabetize facet order by labels.

app/forms/hyrax/forms/batch_upload_form.rb, app/forms/scholars_archive/article_work_form_behavior.rb, app/forms/scholars_archive/default_work_form_behavior.rb, app/forms/scholars_archive/etd_work_form_behavior.rb, app/forms/scholars_archive/oer_work_form_behavior.rb, spec/forms/hyrax/administrative_report_or_publication_form_spec.rb, spec/forms/hyrax/dataset_form_spec.rb, spec/forms/hyrax/default_form_spec.rb, spec/forms/hyrax/eesc_publication_form_spec.rb, spec/forms/hyrax/technical_report_form_spec.rb
=> removed keyword from forms

app/controllers/scholars_archive/handles_controller.rb, config/handles_od_items.yml, spec/requests/scholars_archive/handles_request_spec.rb
=> Add Handle redirects for OD items.

app/controllers/scholars_archive/handles_controller.rb
=> improves handle controller solr queries for FileSet matches

config/routes.rb
=> handle route allows for dots in file parameter

app/controllers/scholars_archive/handles_controller.rb, config/routes.rb
=> adds routes for unhandled traffic

app/assets/stylesheets/osu.scss, app/helpers/hyrax_helper.rb
=> updated style in result list view

config/locales/simple_form.en.yml
Added name formatting helptext to defaults: 
contributor
contributor_advisor
contributor_committeemember
editor
And honors_college_thesis: 
contributor_advisor
=> Added name formatting text to hints

app/forms/scholars_archive/dataset_form_behavior.rb
=> added missing terms in dataset form behavior

config/routes.rb
=> route globbing and directing to homepage

app/controllers/application_controller.rb
=> added https protocol for application helpers

Gemfile, Gemfile.lock, config/sitemap.rb, public/robots.txt
=> added sitemap gem

.gitignore, config/sitemap.rb
- updated gitignore to ignore sitemap files in the public directory
- updated sitemap config to create create index and sitemap files in a shared directory
=> updated gitignore and sitemap config

config/initializers/hyrax_status_list_service_hack.rb
using `ActiveFedora::SolrService` instead of `Hyrax::WorkRelation.new.search_with_conditions` to query for review submissions
=> update query to fix results not being included in the review submissions

app/assets/javascripts/default_datatable_order.js, config/initializers/hyrax_status_list_service_hack.rb
- added fix for `RSolr::Error::Http: RSolr::Error::Http - 414 Request-URI Too Long` on the review submissions queue
- updated js to default review submissions datatable order to `Submission Date`
=> updated submissions query to fix long uri error

lib/tasks/set_conference_name.rake
=> [WIP] added task to set conference name based on known dspace collection

config/authorities/other_affiliation.yml
=> added URI for OSU Superfund Research Prog in local authority

config/handles_ir_communities_collections.yml
Add Community Handle redirect for Pacific Northwest Insect Management Conference
=> Add Community Handle redirect

config/handles_ir_communities_collections.yml
Add more missing Collections Handles (and 1 Community Handle)
=> Add more missing Handles.

config/authorities/degree_name.yml
Fix degree name spelling that @simholt caught
=> Fix spelling

config/handles_ir_communities_collections.yml
I think I copy/pasted the wrong URL last time, it was correct in notes in #1141.
=> Fix Faculty Senate Community Handle

app/actors/scholars_archive/actors/add_other_field_option_actor.rb, app/actors/scholars_archive/actors/nested_fields_operations_actor.rb, app/assets/stylesheets/osu.scss, app/helpers/application_helper.rb, app/indexers/default_work_indexer.rb, app/inputs/multi_value_label_url_input.rb, app/inputs/multi_value_select_other_input.rb, app/models/nested_related_items.rb, app/renderers/hyrax/renderers/search_and_external_link_attribute_renderer.rb, app/views/hyrax/base/_form.html.erb, app/views/hyrax/base/_form_scholars_archive_error.html.erb, config/locales/simple_form.en.yml, spec/views/records/edit_fields/_nested_related_items.html.erb_spec.rb
- implemented validate method for nested_related_items (ended up moving it to the `add_other_field_option_actor.rb` so that it works together with other validation methods in this actor)
- fixed `app/views/hyrax/base/_form.html.erb` to display error messages at the top of the form (rebased from latest build of hyrax)
- added a new partial `app/views/hyrax/base/_form_scholars_archive_error.html.erb` that contains error messages related to our validation methods in `add_other_field_option_actor.rb` and enabled it at `app/views/hyrax/base/_form.html.erb`
=> added validation for related items

config/handles_ir_communities_collections.yml
=> Add remaining Handle redirects for Communities with sub-Communities.

config/authorities/other_affiliation.yml
Added Center for Research on Lifelong STEM Learning.
=> Added new other affiliation

app/views/hyrax/base/_form.html.erb, config/locales/simple_form.en.yml, spec/views/hyrax/base/_form_instructions_spec.rb
Fixes #1111 
Message is present on all forms, including edit. Text is in locale file for easier editing.
=> Add LibGuide link to forms.

app/controllers/scholars_archive/handles_controller.rb, config/handles_mismatched_items.yml
=> Add mismatch handle between DSpace and Hyrax to redirect

config/workflows/honorscollege.json
honors college requires a workflow similar to the graduate school, but we want the labels for workflow steps to reflect honors college rather than grad school.
=> Add Honors College Workflow

sa_scripts/collection_community_cleanup.rake
=> includes cleanup script for posterity sake

Gemfile, Gemfile.lock, config/local_env.example.yml, config/newrelic.yml
=> adds NewRelic gem and configuration

config/newrelic.yml
=> disable NewRelic for development environment

app/models/default.rb
=> Update human_readable_type on Default model.

config/initializers/hydra_access_controls_visibility_hack.rb, spec/models/default_spec.rb
=> Public default visibility

app/views/graduate_thesis_or_dissertations/edit_fields/_license.html.erb, spec/views/graduate_thesis_or_dissertations/edit_fields/_license.html.erb_spec.rb
=> customizes list of licenses avialable for GTDs

app/views/hyrax/base/_form_visibility_component.html.erb, lib/scholars_archive/embargoes/embargo_releaser.rb, lib/tasks/expire_embargoes.rake
Fixes #1180 Sets the code in place to expire embargoes.
Asana ticket for this is found here: https://app.asana.com/0/298612436621205/541192503369551
Fixes #1042
=> Adds code for expiring embargoes

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/views/layouts/application.html.erb
Fixes #1136 
Turbolinks once again causing unwanted side effects in our app.
=> removes jerk turbolinks

app/assets/javascripts/default_datatable_order.js
Fixes #1132 
I decided to tap into the code that is already altering the review submission page datatable.
=> Default datatable pick set to 50

app/assets/javascripts/tooltips.js
Fixes #1207  an issue with bootstrap require
=> Removes bootstrap require

app/models/concerns/scholars_archive/default_metadata.rb, spec/models/default_spec.rb
=> sets visibility to default as open for new works

app/views/hyrax/homepage/_featured_works.html.erb
=> updates featured works list to match recently uploaded for non-admin users

app/controllers/catalog_controller.rb, app/indexers/default_work_indexer.rb
=> Makes title alpha and reverse alpha sortable

app/views/hyrax/stats/file.html.erb, app/views/hyrax/stats/work.html.erb
fix #1169 Use stats model to get date_available and use them for start date if exists
=> Change stats dates to reflect migration, remove alter of legacy statistics

Gemfile, Gemfile.lock
=> Rollback sidekiq for redis commands

app/views/hyrax/stats/file.html.erb, app/views/hyrax/stats/work.html.erb
=> bugfix to parse string datetimes before printing them in a different format

app/assets/javascripts/default_datatable_order.js
Fixes the code for the dropdown preset
=> follow api for datatable in hyrax

app/views/hyrax/base/_form_progress.html.erb
use partial from version of `2.0.0` for now
=> updated form progress view to correct current version

config/authorities/other_affiliation.yml
Added Undergraduate Research Apprenticeship Program.
=> Added new non-academic other

lib/scholars_archive/embargoes/embargo_releaser.rb
=> Embargo expire fix

lib/tasks/bulk_update_csv.rake
fixes #1247 
have processed many updates on the google spreadsheet, see logs for details if needed
=> Bulk update

app/controllers/concerns/scholars_archive/purchased_e_resource_works_controller_behavior.rb, app/controllers/hyrax/purchased_e_resources_controller.rb
https://github.com/osulp/Scholars-Archive/pull/1257 Should be merged first since this will break the forms on the purchased e resource until that PR is merged. This is just an enhancement for that to remove the bum default values on the purchased e resources.
=> Removes default values

app/indexers/purchased_e_resource_indexer.rb
=> configures purchased e resource indexer

app/assets/stylesheets/osu.scss
=> Updates style to fix overlaid button

app/actors/scholars_archive/actors/add_other_field_option_actor.rb
=> update add_other_field_option_actor to skip nil values during validation

config/authorities/other_affiliation.yml
=> Added new other affilication

Gemfile.lock
`bundle update rails` to get the latest dependency updates from rails
=> update rails to get latest security updates

app/services/scholars_archive/edtf_date_compare_service.rb
=> updated date_in_past_five_years? to check that input dates are present

config/authorities/other_affiliation.yml
Added Beginning Researchers Support Program and Continuing Researchers Support Program.
=> added two new non-aca others

app/forms/hyrax/honors_college_thesis_form.rb, app/forms/hyrax/undergraduate_thesis_or_project_form.rb
=> Updates required fields for undergrad and honors

app/assets/stylesheets/osu.scss, app/views/shared/_select_work_type_help.html.erb, app/views/shared/_select_work_type_modal.html.erb
=> adds help text to the bottom of the work type selection modal

app/views/records/edit_fields/_academic_affiliation.html.erb
=> expose dates related to academic units for admins

app/actors/scholars_archive/actors/add_other_field_option_actor.rb, app/authorities/scholars_archive/extended_file_based_authority.rb, app/services/scholars_archive/degree_grantors_service.rb, app/views/records/edit_fields/_degree_grantors.html.erb, config/authorities/degree_grantors.yml, config/initializers/hyrax.rb, spec/authorities/scholars_archive/extended_file_based_authority_spec.rb, spec/services/scholars_archive/degree_grantors_service_spec.rb
=> adds missing degree grantors

app/assets/stylesheets/osu.scss, app/views/hyrax/base/_form.html.erb, config/locales/simple_form.en.yml, spec/views/hyrax/base/_form_instructions_spec.rb
fixes #1276 
@simholt collaborated and approved (tm)
=> makes the help details more noticable

app/actors/scholars_archive/actors/add_other_field_option_actor.rb, spec/actors/scholars_archive/actors/add_other_field_option_actor_spec.rb
Updates the actor to persist other options values when available
=> updated add_other_field_option_actor to persist other options properly

.gitignore, config/initializers/application_revision.rb, config/local_env.example.yml
fixes bug on server to find path to revisions.log file, ignore public/branding in prep for hyrax 2.1.0
=> adds file path to local_env

app/assets/javascripts/application.js, app/views/layouts/_head_tag_content.html.erb, config/tinymce.yml
fixes #1156 
This is a bugfix related to https://github.com/samvera/hyrax/issues/2273. Overriding this partial should be removed as soon as that issue is fixed.
=> tinyMCE ui to properly provide image attachment, bugfix until upstream fixed

app/views/shared/_select_work_type_help.html.erb, config/locales/dataset.en.yml, config/locales/default.en.yml, config/locales/graduate_project.en.yml, config/locales/graduate_thesis_or_dissertation.en.yml, config/locales/honors_college_thesis.en.yml, config/locales/undergraduate_thesis_or_project.en.yml
=> Select worktype text

config/authorities/other_affiliation.yml
Center for Small Farms and Community Food Systems
Kiewit Center for Infrastructure and Transportation
Collaborative Robotics and Intelligent Systems (CoRIS) Institute
=> Added three new non-aca other affiliations

app/assets/stylesheets/osu_settings.scss, app/views/layouts/_head_tag_content.html.erb, config/locales/administrative_report_or_publication.en.yml, config/locales/article.en.yml, config/locales/conference_proceedings_or_journal.en.yml, config/locales/default_work.en.yml, config/locales/eesc_publication.en.yml, config/locales/oer.en.yml, config/locales/open_educational_resource.en.yml, config/locales/purchased_e_resource.en.yml, config/locales/technical_report.en.yml
=> fixes worktype labels and a bug in the head tag content

app/assets/stylesheets/osu.scss, app/helpers/application_helper.rb, app/views/catalog/_facet_pagination.html.erb, app/views/catalog/_next_page_link.html.erb, app/views/catalog/_previous_page_link.html.erb, config/initializers/configuration_hack.rb, config/initializers/hyrax.rb, spec/features/modal_pagination_spec.rb
Looking for feedback. Refactoring I can see is creating a partial for the `<li><a>` elements cutting down on code duplication.
=> Adds in buttons for selecting pages dynamically

app/views/hyrax/base/_form_metadata.html.erb
=> Changes additional fields button

app/assets/stylesheets/osu.scss
=> Fixes overflow of text covering action button

app/forms/hyrax/undergraduate_thesis_or_project_form.rb
=> Removes duplicate fields

app/views/hyrax/base/_form_scholars_archive_error.html.erb
=> Adds error to scholars archive errors list

app/forms/scholars_archive/default_work_form_behavior.rb
=> Reorder conference metadata

app/views/hyrax/stats/file.html.erb
=> Use parent work date_available for file stats

config/locales/hyrax.en.yml
=> Update ingest notice after upload

app/forms/scholars_archive/default_work_form_behavior.rb
=> Reorder conference

app/indexers/default_work_indexer.rb, app/models/solr_document.rb, app/presenters/concerns/scholars_archive/default_presenter_behavior.rb, app/services/scholars_archive/degree_field_service.rb
Fixes #1301
Displays the degree field label.
=> Makes degree_field label show up

app/forms/scholars_archive/article_work_form_behavior.rb
Fixes #1300 
I missed article, so here is the fix for that.
=> Fixes article

sa_scripts/process_legacy_stats.rake
=> Revise legacy stats process

app/controllers/application_controller.rb
=> fixes bugged override

app/assets/stylesheets/osu.scss
=> enforces word-break to make long metadata values behave

lib/tasks/bulk_update_csv.rake
updates supporting the bulk changes in tickets #1376 
fixes #1376
=> support for more types of bulk work changes

app/actors/scholars_archive/actors/add_other_field_option_actor.rb, app/forms/scholars_archive/default_work_form_behavior.rb, app/services/scholars_archive/field_validation_service.rb, spec/actors/scholars_archive/actors/add_other_field_option_actor_spec.rb, spec/scholars_archive/validators/other_option_degree_validator_spec.rb
fixes `NoMethodError: undefined method title' for nil:NilClass` on create
related: https://github.com/osulp/Scholars-Archive/issues/1383
=> update actor add_other_field_option and degree field validation

app/assets/stylesheets/osu.scss
=> Add temporary override to hide Explore Collections tab.

app/actors/scholars_archive/actors/add_other_field_option_actor.rb, app/services/scholars_archive/field_validation_service.rb
=> updated logic for sending notifications on other options

app/models/batch_upload_item.rb
fixes #1392 for production deployment
=> bugfix for batch upload

app/forms/scholars_archive/article_work_form_behavior.rb, app/forms/scholars_archive/default_work_form_behavior.rb, app/forms/scholars_archive/etd_work_form_behavior.rb, app/forms/scholars_archive/oer_work_form_behavior.rb
=> remove identifier from forms and expose for admin

app/forms/scholars_archive/dataset_form_behavior.rb
=> Adds description field to dataset if admin

app/forms/scholars_archive/etd_work_form_behavior.rb, spec/forms/hyrax/graduate_project_form_spec.rb, spec/forms/hyrax/graduate_thesis_or_dissertation_form_spec.rb
=> makes academic affiliation a required field

config/authorities/degree_name.yml
=> Added new degree name

app/views/hyrax/homepage/_featured_fields.html.erb, app/views/hyrax/homepage/_recent_document.html.erb, config/locales/hyrax.en.yml
=> replaces keyword with subject on featured works and recent uploads

Gemfile, Gemfile.lock, config/newrelic.yml
=> New relic again

app/views/records/edit_fields/_academic_affiliation.html.erb
=> Academic affiliation fills normally

Gemfile, Gemfile.lock, app/services/scholars_archive/records_by_user_group_and_visibility.rb, spec/services/scholars_archive/records_by_user_group_and_visibility_spec.rb
=> use facet fields to improve speed of facet pagination functionality

app/services/scholars_archive/records_by_user_group_and_visibility.rb
=> fixes when the user is not logged in

lib/tasks/bulk_update_csv.rake
fixes a bug with bulk updating ActiveTriple::Relation fields
=> sets nil if the property has no remaining values

app/controllers/catalog_controller.rb
=> remove decades from advanced search

app/controllers/catalog_controller.rb
=> Set facet limits back to 5

app/controllers/catalog_controller.rb
Also add to the "All Fields" field
Fixes #1483
=> Add search fields for Advisor and Committee Member

app/forms/scholars_archive/article_work_form_behavior.rb, app/forms/scholars_archive/dataset_form_behavior.rb, app/forms/scholars_archive/default_work_form_behavior.rb, app/forms/scholars_archive/etd_work_form_behavior.rb, app/forms/scholars_archive/oer_work_form_behavior.rb
Fixes #1504 
The fields are unordered at this moment. If we want order, this will take a bit more work.
=> Makes all fields available to admin

app/forms/scholars_archive/article_work_form_behavior.rb, app/forms/scholars_archive/dataset_form_behavior.rb, app/forms/scholars_archive/default_work_form_behavior.rb, app/forms/scholars_archive/etd_work_form_behavior.rb, app/forms/scholars_archive/oer_work_form_behavior.rb
Reverts osulp/Scholars-Archive#1530
Several new issues were introduced.
=> Revert "Makes all fields available to admin"

lib/scholars_archive/embargoes/embargo_releaser.rb
This adds the beginnings of a reworked embargo release task.
=> [WIP] Update embargo task to log and use embargo actor

app/views/hyrax/base/_attribute_rows.html.erb
=> Funding statement render just as text, not link.

Gemfile, Gemfile.lock, config/environments/development.rb, config/initializers/datadog-tracer.rb, config/initializers/lograge.rb
=> adds datadog and lograge for monitoring and logging improvements

app/assets/javascripts/ordered_creator.js, app/assets/stylesheets/osu.scss, app/inputs/multi_value_ordered_input.rb, config/initializers/hyrax.rb
- added css changes to align `up` and `down` buttons
Screenshot:
=> updated style for up and down arrows

config/initializers/datadog-tracer.rb
=> increases DataDog tracing

app/models/concerns/scholars_archive/has_solr_labels.rb, app/models/solr_document.rb, app/services/scholars_archive/ordered_parser_service.rb, spec/services/scholars_archive/ordered_parser_service_spec.rb
Reconfigures the nested_ordered_creator_label to include the index of the object, and adds a parser/sorter to parse index and sort labels based on index.
=> Sorts on the show page

app/views/hyrax/base/_work_description.erb, spec/views/hyrax/base/_work_description.erb_spec.rb
=> Change Citeable URL to https, update spec.

app/forms/hyrax/forms/batch_upload_form.rb
hide old creator metadata in batch upload form
=> removed old creator in batch_upload_form

app/assets/javascripts/nested_field.js.coffee
=> make ids unique when resetting nested ordered creator items on load

app/assets/stylesheets/osu.scss
=> fixes style of dd-list item while being dragged

app/controllers/application_controller.rb, app/controllers/scholars_archive/handles_controller.rb, config/local_env.example.yml
=> reworks HTTP header based API authentication

app/assets/javascripts/nested_field.js.coffee
=> Fixes the duping issue with the items

lib/tasks/bulk_update_csv.rake
This is to facilitate bulk updates that include multiple value fields
=> adds ability to update/add multi-value values

app/models/concerns/scholars_archive/has_nested_ordered_properties.rb, app/models/solr_document.rb, spec/models/nested_ordered_title_spec.rb, spec/models/solr_document_spec.rb
fixes https://github.com/osulp/Scholars-Archive/issues/1633
=> [WIP] Feature/keep hyrax expected methods

app/models/concerns/scholars_archive/has_nested_ordered_properties.rb
=> Update to work with string and nested object

app/models/concerns/scholars_archive/default_metadata.rb, app/models/nested_ordered_abstract.rb, app/models/nested_ordered_additional_information.rb, app/models/nested_ordered_contributor.rb, app/models/nested_ordered_creator.rb, app/models/nested_ordered_title.rb, app/models/nested_related_items.rb
=> Sets the predicates properly on the nested items

lib/tasks/bulk_update_csv.rake
=> handles the case where new values are being added to existing multi-value metadata

app/controllers/catalog_controller.rb, app/helpers/hyrax_helper.rb, app/models/concerns/scholars_archive/default_metadata.rb
=> Adds back in creator and contributor as faceted fields

Gemfile, Gemfile.lock
Security updates identified in these two gems
=> gem security updates

app/controllers/catalog_controller.rb
=> Add alt_title to All Fields search

config/deploy.rb
=> symlinks branding directory for deployment

app/forms/hyrax/purchased_e_resource_form.rb
=> update purchase e resource form

config/initializers/session_store.rb
fixes #1508 
https://cwe.mitre.org/data/definitions/614.html
=> force a secure cookie on production or staging

lib/scholars_archive/migrate_ordered_metadata_service.rb
=> bugfix for ordered metadata comparison

config/initializers/session_store.rb
Reverts osulp/Scholars-Archive#1734
=> Revert "force a secure cookie on production or staging"

lib/tasks/fixity_check.rake
=> adds fixity check task

app/views/hyrax/base/_attribute_rows.html.erb, config/locales/simple_form.en.yml
=> make depositor visible by admin

app/controllers/concerns/scholars_archive/works_controller_behavior.rb
fixes #1696 
See slack channel for video demonstrating it in action
=> redirects a work to its proper route

app/views/hyrax/base/_attribute_rows.html.erb
=> use new lonely operator for simplified if statement

app/forms/hyrax/forms/collection_form.rb
This is the first step in fixing #1751 There is some more work to be done to fix that ticket completely. A separate ticket for adding nested related items to the collection model.
=> Removes fields from collections

app/views/hyrax/base/_form_metadata.html.erb
=> displays representative media for datasets

Gemfile.lock
=> Rack gem update

app/models/concerns/scholars_archive/has_nested_ordered_properties.rb, app/services/scholars_archive/label_and_ordered_parser_service.rb, app/services/scholars_archive/ordered_parser_service.rb, spec/models/default_spec.rb, spec/services/scholars_archive/label_and_ordered_parser_service_spec.rb, spec/services/scholars_archive/ordered_parser_service_spec.rb
Fixes #1773 
Currently seeing weird behavior on the added spec.
=> Change sort by to use integer values.

app/inputs/multi_value_ordered_input.rb, spec/inputs/multi_value_ordered_input_spec.rb
This updates the input class used in the forms to render existing ordered items properly
Related to #1774 #1773
=> updated input multi_value_ordered_input

config/authorities/other_affiliation.yml
Added Openly Published Environmental Sensing Lab and Louis Stokes Academy for Minority Participation.
=> Added new other affiliations

app/assets/javascripts/hyrax/browse_everything.js
=> bugfix for browseeverything to load without depending on turbolinks

lib/scholars_archive/migrate_ordered_metadata_service.rb, lib/tasks/migrate_works_10_or_more_items.rake
Main tasks (R1 and R2) are ready to be run in sequence. Each run will fix issues described in https://github.com/osulp/Scholars-Archive/issues/1796#issuecomment-472153744
- Task 1 (R1) can be used to migrate and fix works with creators that have the incorrect characters
```
bundle exec rake scholars_archive:migrate_dspace_creator_char_cleanup
``` 
- Task 1 (R2) can be used to migrate and fix creators that have incorrect order for including creators with 10+ items
```
bundle exec rake scholars_archive:migrate_dspace_creator_order_cleanup
``` 
- Task 2 was used to separate those works that @simholt already had fixed. The task  was useful to build groups `X` and `Y`. It also gave me the counts in https://github.com/osulp/Scholars-Archive/issues/1796#issuecomment-471065208
```
bundle exec …
```
=> Tasks to force migration on handles with wrong order and invalid chars in creator field

lib/tasks/migrate_works_10_or_more_items.rake
related to #1796 
moving rescue, including logger info, up to the main task to catch other issues when forcing a migration
=> refactor logger and fix undefined method

app/renderers/hyrax/renderers/search_and_external_link_attribute_renderer.rb, spec/renderers/hyrax/renderers/search_and_external_link_attribute_renderer_spec.rb
=> uri bugfix for search and external link renderer

.circleci/config.yml, Dockerfile, Gemfile, config/initializers/clamav.rb
=> adds clamav

.circleci/config.yml, Dockerfile, build/entrypoint.sh, build/firstrun.sh, build/install_gems.sh, build/validate_migrated.sh, config/blazegraph/RWStore.properties, config/fedora.yml, docker-compose.override.example.yml, docker-compose.yml
This brings SA up to date with docker-compose and in line with how OD2 behaves for development (which is better overall). 
Will require you to kill your docker volumes for SA and rebuild.
=> updates docker image, compose, services

Gemfile.lock, config/puma/development.rb, docker-compose.yml, spec/rails_helper.rb
**NOTE** : Remove or comment out from `local_env.yml`:
`SCHOLARSARCHIVE_SOLR_URL`
`SCHOLARSARCHIVE_FEDORA_URL`
`SCHOLARSARCHIVE_DB_HOST`
=> fixes docker dependencies for development and test

lib/tasks/bulk_update_csv.rake
=> allows for bulk updating ordered metadata

lib/tasks/bulk_update_csv.rake
bugs found on staging are addressed here.
Generally speaking, the `work.nested_ordered_* = nil` aims to clear out the values for the metadata only be be replaced by the following line `work.nested_ordered_*_attributes = ...` with adjusted ordered values.
=> improves bulk update task and fixes ordered property bugs

app/views/hyrax/admin/workflows/index.html.erb, spec/views/hyrax/admin/workflows/index.html.erb_spec.rb
=> update date modified format in admin workflows index view

Gemfile, Gemfile.lock, config/initializers/clamav.rb
=> disables clamav until it can be verified to work on production

app/views/hyrax/base/_attribute_rows.html.erb
=> remove preformatting of abstract code

app/assets/javascripts/default_datatable_order.js, app/assets/javascripts/embargo_date_field.js, app/assets/javascripts/embargo_reason_field.js, app/assets/javascripts/hyrax/browse_everything.js, app/assets/javascripts/tooltips.js
Blacklight on load Fixes #1805
=> transition from turbolinks to blacklight

lib/scholars_archive/embargoes/embargo_releaser.rb
=> fixes day of embargo expiring issue

app/helpers/workflows_index_helper.rb, app/views/hyrax/admin/workflows/index.html.erb, spec/helpers/workflows_index_helper_spec.rb
=> Add local time from utc helper

app/views/hyrax/base/_form_visibility_component.html.erb
=> Separate Ongoing Research and Pending Publication

Gemfile.lock
=> run bundle install for honeycomb

config/authorities/other_affiliation.yml
=> Add new other affiliation

app/views/hyrax/base/_form_visibility_component.html.erb
=> adds embargo reason when editing work

app/assets/javascripts/tooltips.js
=> updates popup

app/assets/stylesheets/osu.scss, app/views/hyrax/base/_social_media.html.erb, spec/views/hyrax/base/_social_media.html.erb_spec.rb
=> Social media: update button text, style, and alignment

app/views/hyrax/base/_social_media.html.erb
=> update copy single use link class

Gemfile, Gemfile.lock
This is to revert to our current version of puma on production.
=> regress puma to 3.12.1

app/assets/stylesheets/osu.scss, app/views/layouts/application.html.erb
=> import and set open sans

app/assets/stylesheets/osu.scss, app/views/hyrax/base/_form_visibility_component.html.erb
=> update spacing on visibility panel

app/indexers/default_work_indexer.rb
=> skip works with empty embargo_history

lib/tasks/bulk_update_csv.rake
=> rescue errors during bulk updates

lib/scholars_archive/embargoes/embargo_releaser.rb
=> update embargo_releaser to catch error during embargo lifting task

app/views/hyrax/base/_form_rendering.html.erb, app/views/hyrax/base/_form_representative.html.erb, app/views/hyrax/base/_form_thumbnail.html.erb, app/views/records/edit_fields/_dates_section.html.erb
=> updates view for dates and media on edit

app/assets/stylesheets/osu.scss, app/views/scholars_archive/base/_form_date_field.html.erb
=> date remove button normalization

app/views/hyrax/base/show.html.erb
=> remove bottom workflow actions

app/assets/html/500.html.haml
=> update new 500 error text

app/views/hyrax/base/_citations.html.erb
=> remove broken links

config/authorities/licenses.yml
=> adds licenses

.rubocop_fix_me.yml, app/renderers/hyrax/renderers/external_link_attribute_renderer.rb, app/views/hyrax/base/_attribute_rows.html.erb, spec/renderers/hyrax/renderers/external_link_attribute_renderer_spec.rb
=> handle link is external now

app/views/advanced/_advanced_search_fields.html.erb
=> sort based on metadata name

app/services/scholars_archive/degree_level_service.rb
=> update honors college thesis to only bachelors

app/views/advanced/_advanced_search_form.html.erb, app/views/advanced/index.html.erb
=> moves advanced search buttons and adds search to top

app/assets/stylesheets/osu.scss
=> update search result container length

app/assets/stylesheets/osu.scss
=> update form length

config/authorities/degree_name.yml
Professional Science Masters in Fisheries and Wildlife Administration
=> Add new Professional Science Masters

app/controllers/scholars_archive/citations_controller.rb, app/views/hyrax/base/_citations.html.erb, app/views/scholars_archive/citations/apa.html.erb, app/views/scholars_archive/citations/chicago.html.erb, app/views/scholars_archive/citations/mla.html.erb, config/routes.rb
=> link citations in citation dropdown

config/sitemap.rb, public/robots.txt
=> update sitemap config to compress all but first sitemaps

app/helpers/hyrax_helper.rb, app/helpers/oregon_digital/citations_behavior.rb, app/helpers/oregon_digital/formatters/apa_formatter.rb, app/helpers/oregon_digital/formatters/chicago_formatter.rb, app/helpers/oregon_digital/formatters/mla_formatter.rb
=> Set up date issued for citations

app/views/hyrax/base/_form_progress.html.erb
=> swap button text to submit

app/models/ability.rb
=> add edit ability to check if admin set of solr doc includes current user

app/models/solr_document.rb
=> initial refactor for parsed labels

app/models/nested_geo.rb, app/models/nested_ordered_abstract.rb, app/models/nested_ordered_additional_information.rb, app/models/nested_ordered_contributor.rb, app/models/nested_ordered_creator.rb, app/models/nested_ordered_resource.rb, app/models/nested_ordered_title.rb, app/models/nested_related_items.rb
=> refactor nested objects to inherit from a base resource.

config/locales/hyrax.en.yml
=> updated notification

app/views/hyrax/base/_show_actions.html.erb
=> make it so tombstone button only shows up if deposited

app/views/hyrax/base/_show_actions.html.erb, config/workflows/default_workflow.json, config/workflows/self_deposit.json
=> update default single step deposits to have tombstone

.rubocop_fix_me.yml, app/models/concerns/scholars_archive/default_terms.rb
Reverts osulp/Scholars-Archive#2076
=> Revert "add right terms to defaults"

app/assets/stylesheets/osu.scss, app/views/hyrax/base/_tombstoned_work.html.erb
Reverts osulp/Scholars-Archive#2069
=> Revert "more refined view"

app/views/hyrax/base/_show_actions.html.erb, config/workflows/default_workflow.json, config/workflows/self_deposit.json
Reverts osulp/Scholars-Archive#2074
=> Revert "update default single step deposits to have tombstone"

app/views/hyrax/base/_show_actions.html.erb
Reverts osulp/Scholars-Archive#2067
=> Revert "make it so tombstone button only shows up if deposited"

app/controllers/scholars_archive/content_blocks_controller.rb, app/views/hyrax/base/_tombstoned_work.html.erb
Reverts osulp/Scholars-Archive#2065
=> Revert "updates to use html"

app/helpers/hyrax_helper.rb, app/helpers/oregon_digital/citations_behavior.rb, app/helpers/oregon_digital/formatters/apa_formatter.rb, app/helpers/oregon_digital/formatters/chicago_formatter.rb, app/helpers/oregon_digital/formatters/mla_formatter.rb, app/views/hyrax/base/_tombstoned_work.html.erb
Reverts osulp/Scholars-Archive#2064
=> Revert "Feature/tombstone ui"

app/models/solr_document.rb
Reverts osulp/Scholars-Archive#2050
=> Revert "initial refactor for parsed labels"

.rubocop_fix_me.yml, app/models/ability.rb
This addresses #2093
It updates the ability to allow a current user that is an admin to edit a work.
=> updates to allow admin to edit works

Gemfile, Gemfile.lock
upgrade honeycomb-beeline from 1.0.0 -> 2.0.0
=> upgrade honeycomb beeline -> 2.0.0

docker-compose.yml
Fixes #2051
This works and more closely aligns with the config for Circle.
=> Change Docker Solr tag to 6-slim

.rubocop_fix_me.yml, app/controllers/hyrax/administrative_report_or_publications_controller.rb, app/controllers/hyrax/articles_controller.rb, app/controllers/hyrax/conference_proceedings_or_journals_controller.rb, app/controllers/hyrax/datasets_controller.rb, app/controllers/hyrax/defaults_controller.rb, app/controllers/hyrax/eesc_publications_controller.rb, app/controllers/hyrax/graduate_projects_controller.rb, app/controllers/hyrax/graduate_thesis_or_dissertations_controller.rb, app/controllers/hyrax/honors_college_theses_controller.rb, app/controllers/hyrax/open_educational_resources_controller.rb, app/controllers/hyrax/purchased_e_resources_controller.rb, app/controllers/hyrax/technical_reports_controller.rb, app/controllers/hyrax/undergraduate_thesis_or_projects_controller.rb, app/services/hyrax/workflow/deletion_approval_notification.rb, app/services/hyrax/workflow/deletion_request_rejection_notification.rb, app/services/hyrax/workflow/metadata_only_record.rb, app/services/hyrax/workflow/pending_deletion_notification.rb, app/views/hyrax/base/_show_actions.html.erb, config/workflows/datasets.json, config/workflows/gtd.json, config/workflows/honorscollege.json, config/workflows/one_step.json, config/workflows/stakeholder.json, docker-compose.yml, spec/services/hyrax/workflow/deletion_approval_notification_spec.rb, spec/services/hyrax/workflow/deletion_request_rejection_notification_spec.rb, spec/services/hyrax/workflow/pending_deletion_notification_spec.rb
Reverts osulp/Scholars-Archive#2091
=> Revert "Revert "Tombstone mechanism in place" Merge #2090 first"

app/controllers/application_controller.rb, app/controllers/scholars_archive/content_blocks_controller.rb, app/services/hyrax/workflow/metadata_only_record.rb, app/views/hyrax/base/_tombstoned_work.html.erb, app/views/hyrax/base/show.html.erb, config/routes.rb
Reverts osulp/Scholars-Archive#2088
1 of 7 PRs to revert related to https://github.com/osulp/Scholars-Archive/issues/1801 and https://github.com/osulp/Scholars-Archive/pull/2094
=> Revert "Revert "Feature/refine tombstone""

app/helpers/hyrax_helper.rb, app/helpers/scholars_archive/citations_behavior.rb, app/helpers/scholars_archive/citations_behaviors/formatters/apa_formatter.rb, app/helpers/scholars_archive/citations_behaviors/formatters/chicago_formatter.rb, app/helpers/scholars_archive/citations_behaviors/formatters/mla_formatter.rb, app/views/hyrax/base/_tombstoned_work.html.erb
Reverts osulp/Scholars-Archive#2086
2 of 7 PRs to revert related to #1801 and #2094
=> Revert "Revert "Feature/tombstone ui""

app/views/hyrax/base/_show_actions.html.erb
Reverts osulp/Scholars-Archive#2084
4 of 7 PRs to revert related to #1801 and #2094
=> Revert "Revert "make it so tombstone button only shows up if deposited""

app/controllers/scholars_archive/content_blocks_controller.rb, app/views/hyrax/base/_tombstoned_work.html.erb
Reverts osulp/Scholars-Archive#2085
3 of 7 PRs to revert related to #1801 and #2094
=> Revert "Revert "updates to use html""

app/services/hyrax/indexes_thumbnails.rb, app/services/hyrax/workflow/metadata_only_record.rb, app/views/hyrax/base/_show_actions.html.erb, config/locales/hyrax.en.yml
Reverts osulp/Scholars-Archive#2082
5 of 7 PRs to revert related to #1801 and #2094
=> Revert "Revert "Feature/file set delete ldp gone tombstone""

app/views/hyrax/base/_show_actions.html.erb, config/workflows/default_workflow.json, config/workflows/self_deposit.json
Reverts osulp/Scholars-Archive#2081
6 of 7 PRs to revert related to #1801 and #2094
=> Revert "Revert "update default single step deposits to have tombstone""

app/assets/stylesheets/osu.scss, app/views/hyrax/base/_tombstoned_work.html.erb
Reverts osulp/Scholars-Archive#2080
7 of 7 PRs to revert related to #1801 and #2094
=> Revert "Revert "more refined view""

config/initializers/hyrax_status_list_service_hack.rb
fixes https://github.com/osulp/Scholars-Archive/issues/2036
update filter_condition variable to also hide works with workflow state set to "tombstoned" from the list
=> update filter_condition to remove tombstoned works from review table

lib/hyrax/controlled_vocabularies/location.rb, spec/hyrax/controlled_vocabularies/location_spec.rb
fixes https://github.com/osulp/Scholars-Archive/issues/1694
based on PRs https://github.com/OregonDigital/OD2/pull/1125 and https://github.com/OregonDigital/OD2/pull/1138 (by @CGillen) to fix https://github.com/OregonDigital/OD2/issues/1124
=> add parent_hierarchy to location based on OD2/issues/1124

app/models/ability.rb
=> update ability.rb to check if record responds to admin_set on edit

config/environments/development.rb, docker-compose.yml
fixes issues (b) and (c) in https://github.com/osulp/Scholars-Archive/issues/1972#issuecomment-662685752 found while debugging https://github.com/osulp/Scholars-Archive/issues/1972 
- add default values for FITS_PATH, RAILS_CACHE_STORE_URL, and ACTIVE_JOB_QUEUE_ADAPTER
- update default value for SCHOLARSARCHIVE_TRIPLESTORE_ADAPTER_URL to fix blazegraph issues 
- add `config.web_console.whitelisted_ips` helpful for local debugging
=> update dev environment to fix solr and blazegraph issues

config/handles_ir_communities_collections.yml
=> Add encoded quotes around solr query to stop error

config/initializers/hacks/hydra_derivatives_processors_image_hack.rb
=> Combine imagemagick calls and force TrueColor type during mogrification

config/initializers/hyrax.rb, config/initializers/proxy_deposit_request_hack.rb
=> Link ownership change request message to fully qualified site path

app/views/catalog/_facet_pagination.html.erb
=> Fix span closing tags on facet modal

app/assets/javascripts/application.js, app/assets/javascripts/hyrax/save_work/required_fields.es6
=> Add JS validation that checks for embargo date

app/assets/stylesheets/osu.scss
=> Remove :before and :after psuedo-content from preformatted values

app/assets/javascripts/embargo_reason_field.js
=> Add JS to disable/enable embargo fields

app/views/hyrax/base/show.html.erb
=> Add nil check on workflow state work show page

app/views/hyrax/base/_show_actions.html.erb, app/views/scholars_archive/base/_modal_request_delete.html.erb, config/locales/hyrax.en.yml
=> Add modal for request deletion workflow

app/views/hyrax/base/_show_actions.html.erb
=> Add another nil check for workflow state name

config/authorities/other_affiliation.yml
Added Cooperative Institute for Marine Resource Studies
=> Add new affiliation

Gemfile, Gemfile.lock
Reverts osulp/Scholars-Archive#2164
Reverting until more testing can be done on staging, in order to deploy separate changes now.
=> Revert "Pin mini_racer to 0.2.6"

app/controllers/catalog_controller.rb
=> Capitalize sort option labels

.rubocop_fix_me.yml, app/assets/stylesheets/osu.scss, app/controllers/catalog_controller.rb, app/indexers/default_work_indexer.rb
This allows users to search extracted text and highlight that text in the results
Fixes #1408
=> Index fileset text extraction on works

app/assets/stylesheets/osu.scss
=> Restore multivalue metadata remove button

app/controllers/catalog_controller.rb
Adds a search field so Series metadata links to correct search instead of the general All Fields search
Fixes #1580
=> Add in_series search field

app/models/solr_document.rb
=> Convert SolrDocument dates to local timezone

lib/tasks/bulk_update_csv.rake
=> Add parentheses for methods with arguments.

app/views/hyrax/homepage/_explore_collections.html.erb
=> Convert collection thumbnail to string to handle nil case

lib/tasks/remove_abstract_and_title_data.rake
=> Add logging when unordered fields exist but no ordered field equivalent

app/models/oai_set.rb
=> Remove 'isPartOf_ssim' from setSpec and fix #from_spec

lib/tasks/bulk_ingest_csv.rake
=> Set work visibility to visibility column if exists

lib/tasks/bulk_ingest_csv.rake
Set file set visibility to work visibility
Fixes #2250
=> Change bulk ingest UploadedFile instantiation so the file is not skipped

lib/tasks/bulk_ingest_csv.rake
=> Add support for nested_related_items to bulk ingest

config/workflows/gtd.json, config/workflows/honorscollege.json
=> Make sure works stay deactived in two step approval workflows

app/controllers/catalog_controller.rb, app/indexers/default_work_indexer.rb, solr/conf/schema.xml, solr/config/schema.xml
Reconfigure catalog controller and work indexer for new *_sfacet fields
=> Add new solr field for alphasorted facets

app/indexers/default_work_indexer.rb
Indexs *_sfacet values. We will merge a new PR that enables *_sfacet facet fields once things are reindex everywhere.
#1809
=> Re-enable *_sfacet indexing

config/locales/hyrax.en.yml
=> use spotlight instead of featured researcher

app/assets/javascripts/hyrax/browse_everything.js
=> Add JS to remove BrowseEverything modal on cancel/submit

app/views/hyrax/base/_attribute_rows.html.erb
=> updates alt title to be searchable and hover text properly displays

config/locales/hyrax.de.yml, config/locales/hyrax.es.yml, config/locales/hyrax.fr.yml, config/locales/hyrax.it.yml, config/locales/hyrax.pt-BR.yml, config/locales/hyrax.zh.yml
=> Add translations for footer links

app/assets/javascripts/deactivate_save_button.js
=> Allow checkbox to check again

Gemfile, Gemfile.lock, app/assets/javascripts/advanced_facets.js, app/assets/javascripts/application.js, app/assets/stylesheets/application.css, app/controllers/blacklight_advanced_search/advanced_controller.rb, app/controllers/catalog_controller.rb
=> Add advanced search type-aheads

app/controllers/catalog_controller.rb, app/views/hyrax/collections/_sort_and_per_page.html.erb
Removes slideshow view from collection and search results pages
fixes #1742 
fixes #1821
=> Remove slideshow view

config/initializers/invisible_captcha.rb, docker-compose.yml
=> Configure invisible captcha for multiple rails instances

app/assets/javascripts/advanced_facets.js
=> Remove advanced search type ahead limit

app/controllers/catalog_controller.rb
=> Set facets to use diacritic sortable values

app/assets/javascripts/file_set_versioning.js, app/views/hyrax/file_sets/_versioning.html.erb, config/initializers/hacks/hyrax_filesets_controller_hack.rb
=> Add file name field to file versioning form

config/initializers/proxy_deposit_request_hack.rb
=> Remove broken old hack

docker-compose.yml, solr/conf/schema.xml, solr/conf/solrconfig.xml, solr/config/schema.xml, solr/config/solrconfig.xml
New volume mount location
Updated Solr config (No breaking changes), updating deprecated functionality
=> Upgrade to solr 8

config/initializers/hacks/blacklightoaiprovider_solrdocumentwrapper_hack.rb
=> Remove Collections from OAI-PMH list_records

app/controllers/catalog_controller.rb, app/helpers/hyrax_helper.rb
Fixes #1809 further
Capitalize first letter of each name and downcase affixes (de, la, von, van, etc...)
=> Titleize diacritic sortable facets and downcase surname affixes

config/initializers/hyrax.rb
=> Restore analytics configuration

config/analytics.yml
Reverts osulp/Scholars-Archive#2370
Something else expects this file to be there and errors if not:
```
ActionView::Template::Error (No such file or directory @ rb_sysopen - /data/config/analytics.yml):
```
=> Revert "Remove unused analytics.yml"

app/forms/hyrax/forms/batch_upload_form.rb
=> Change contributor to nested_ordered_contributor

.circleci/config.yml, config/initializers/yabeda.rb, config/prometheus_client.yml
move prometheus client init to initializers/yabeda.rb
=> fix prometheus client data store initialization

.circleci/config.yml
set YABEDA_PROMETHEUS_PATH for the build/push stage
=> fix build/push CCI phase

lib/tasks/fixity_check.rake
Add in & update the old Fixity command that is not working anymore and update with the new one.
=> Add in the new Fixity command

config/initializers/honeycomb.rb
=> Add null Honeycomb config to prevent #append_info_to_payload from getting upset

config/initializers/honeycomb.rb, lib/tasks/fixity_check.rake
Fix the Fixity to include in the new testing command.
=> Fix the Fixity Testing Environment

lib/tasks/fixity_check.rake
=> Override w/ async for Fixity

app/assets/stylesheets/osu.scss, app/controllers/concerns/scholars_archive/works_controller_behavior.rb, app/views/hyrax/base/_items.html.erb, config/routes.rb
In this PR, we add in the `deletion button` to the Works model and delete all `FileSets` via a convenient of a button.
=> Add in deletion all FileSets to Works

app/assets/javascripts/hyrax/save_work/save_work_control.es6, app/assets/stylesheets/osu.scss, app/controllers/concerns/scholars_archive/datasets_controller_behavior.rb, app/controllers/hyrax/datasets_controller.rb, app/forms/scholars_archive/dataset_form_behavior.rb, app/mailers/scholars_archive/human_data_mailer.rb, app/services/scholars_archive/workflow/deposit_received_notification.rb, app/views/hyrax/base/_form_human_subject_data_component.html.erb, app/views/hyrax/base/_form_progress.html.erb, app/views/scholars_archive/human_data_mailer/email_on_human_data.html.erb, config/locales/hyrax.en.yml, config/locales/hyrax.es.yml, config/locales/hyrax.fr.yml
Add in the requirement for new section in the dataset for human subjects data.
=> Add in file for the human data

spec/mailers/scholars_archive/human_data_mailer_spec.rb
Add in the missing rspec testing for the human data email that will send out to reviewer.
=> Add in rspec for human data

app/views/datasets/edit_fields/_rights_statement.html.erb
Add in fixure to the copyright statement in the Dataset where it revert to the selected `No copyright` after you change it.
=> Fix copyright statements bug

app/views/hyrax/base/_items.html.erb
Fixing the routing delete button problem with other works type like undergrad, honor, etc...
=> Add fix to delete route

app/controllers/concerns/scholars_archive/datasets_controller_behavior.rb
Add and adjust code to the behavior control of the `Datasets` to make it optimize with human data.
=> Optimize the code for human data

app/controllers/concerns/scholars_archive/datasets_controller_behavior.rb
Fixing the issue where email cause crash with human data in the datasets
=> Fix the emailing issue with human data

.rubocop_fix_me.yml, Gemfile, Gemfile.lock
=> Update the Gemfile for Rubocop

app/controllers/concerns/scholars_archive/datasets_controller_behavior.rb
Add in only finding the SA email to see if it will find the email.
=> Revert the email to find SA email

app/mailers/application_mailer.rb, app/mailers/scholars_archive/human_data_mailer.rb, spec/mailers/scholars_archive/human_data_mailer_spec.rb
Add in different email recipients to email out to get the alert.
=> Revise email with different mailers

app/controllers/concerns/scholars_archive/datasets_controller_behavior.rb
=> Email all users with edit_user (manager) permissions for Dataset adminset

app/views/hyrax/base/_items.html.erb
Add in a statement to make sure that the content will display only when user is log in.
=> Add in the update to only login user can see it

config/analytics.yml
Change the YML file to be `nil` value in the fallback value area since the SA analytic didn't like the other values.
=> Change fallback value to nil

.dockerignore, Dockerfile, Gemfile, Gemfile.lock
=> Docker build improvements

public/robots.txt
=> Improve robots.txt

app/controllers/hyrax/datasets_controller.rb
Fixes #2032 this sets up a redirect for people to request accesss
=> sets up redirect for embargoed datasets to contact page

app/models/dataset.rb
=> Convert DATACITE_MODEL env var to symbol

Gemfile, Gemfile.lock
=> Remove unused devise-guest gem

config/initializers/hacks/hyrax_file_sets_controller_hack.rb
=> Allow admins to view restricted fileset page

app/assets/stylesheets/osu.scss
Temporary remove the analytic button on SA as it is waiting for work-in-development from Hyrax and staccato with GA4.
=> Remove the analytic button

.rubocop_fix_me.yml, app/models/hyrax/contact_form.rb, config/locales/hyrax.de.yml, config/locales/hyrax.en.yml, config/locales/hyrax.es.yml, config/locales/hyrax.fr.yml, config/locales/hyrax.it.yml, config/locales/hyrax.pt-BR.yml, config/locales/hyrax.zh.yml
Add in a new option for `contact_form` letting user add in a way to request statistic on their work.
=> Add in new option for contact form

config/locales/hyrax.de.yml, config/locales/hyrax.it.yml, config/locales/hyrax.pt-BR.yml, config/locales/hyrax.zh.yml
=> Add more language option towards dataset

app/views/hyrax/admin/workflows/index.html.erb
=> update workflows page to remove published

spec/views/hyrax/admin/workflows/index.html.erb_spec.rb
=> Update submission queue spec to local datetime

app/assets/javascripts/degree_sort.js
Make changes to the `js` file that load the selection `on load` also rather than the `on change` only.
=> Update the degree sort

.rubocop_fix_me.yml, lib/qa/authorities/geonames.rb
Create a new searching way of using the `GeoName ID` to search for the place without typing in the name.
=> Add in search filter with id

app/controllers/concerns/scholars_archive/articles_controller_behavior.rb, app/controllers/hyrax/articles_controller.rb, app/mailers/scholars_archive/articles_notification_mailer.rb, app/views/scholars_archive/articles_notification_mailer/email_article_depositor.html.erb, spec/mailers/scholars_archive/articles_notification_mailer_spec.rb, spec/mailers/scholars_archive/human_data_mailer_spec.rb
`ENHANCEMENT:` Add in a way to send out email letting the user know that their `article` has been `deposited`.
=> Create a mailer to send confirmation for Article

app/views/hyrax/base/_attribute_rows.html.erb
`FIXED:` Add in the display of `other_affiliation` on the show page of the work.
=> Add in display of other affiliation

app/views/hyrax/base/_attribute_rows.html.erb, config/initializers/load_other_affiliation.rb
Add in a fix in display to show the name of the  `other affiliation` rather than just the href link
=> Modify the other affiliation display

app/controllers/concerns/scholars_archive/works_controller_behavior.rb, app/views/records/edit_fields/_other_affiliation.html.erb
`BUG FIX` - Add in a method to retain the data from being lost on the form for `other_affiliation` when selected the `'other' option`.
=> Add in to save data for other affiliation

app/views/hyrax/base/_attribute_rows.html.erb, config/initializers/load_other_affiliation.rb, docker-compose.yml
`CHANGES:` Revert the code back to the original state how it is in the beginning. Discover to be an issue of indexing rather than displaying itself.
Update: The `TripleStore_URL` was the main cause and got it updated to reflect the label to be able to pull.
=> Revert back the original layout of Other Affiliation

app/services/scholars_archive/triple_powered_service.rb
`BUG:` Change one piece of code to accept `other affiliation` that is part of the `LOC` to display on the work show page.
=> Change code to display affiliation

app/controllers/concerns/scholars_archive/redirect_if_restricted_behavior.rb
Fixes #2032 
This removes that last little notification that gets populated during the redirect process.
=> Removes flash notification from redirects.

Dockerfile
=> Install mediainfo and exiftools for fits dependencies

lib/tasks/fixity_check.rake
=> Make fixity check rake task act more like AF find_each and rescue ActiveFedora::ModelMismatch

app/views/hyrax/base/_workflow_actions.html.erb
=> Init TinyMCE again

app/forms/hyrax/forms/collection_form.rb, app/views/hyrax/collections/show.html.erb, config/initializers/hacks/hyrax_collection_search_builder_hack.rb
=> Batch of v3.60 bugfixes

config/initializers/hacks/hyrax_collection_search_builder_hack.rb
=> sort_field wasn't the issue, Hyrax#5905 implements a fix for collection show page sorting

Gemfile, Gemfile.lock, app/mailers/scholars_archive/container_mailer.rb, app/views/scholars_archive/container_mailer/report_email.html.erb, lib/tasks/filesets_inventory_check.rake, spec/mailers/scholars_archive/container_mailer_spec.rb
`STATS:` Create a rake task to go into the archive/container files on SA.
`TASK TO DO`
=> Writing a rake task to do fileset inventory check

lib/tasks/fixity_check.rake
`BUGS:` Update the rake task to count for the `failed id` in fixity.
=> Update fixity to count failed id

app/controllers/concerns/scholars_archive/redirect_if_restricted_behavior.rb, lib/tasks/update_peer_reviewed_data.rake
`UPDATE:` Add in type conversion so `each_slice` can run with integer.
=> Add in conversion to_i for task to run

app/controllers/concerns/scholars_archive/redirect_if_restricted_behavior.rb
`UPDATE:` Fix some statement feedback on the redirect
=> Modify the statement on correction

lib/tasks/filesets_inventory_check.rake
`BUGS:` Update the fileset check task to include if `:mime_type` is not present
=> Update the fileset check

config/initializers/hacks/blacklightoaiprovider_solrdocumentwrapper_hack.rb
`BUGS:` Remove the `!` on `.sub` to let frozen string can be edit.
=> Remove ! to fix frozen string

config/authorities/degree_name.yml
Changed quotes so shows up properly
=> Changed quotes so shows up properly in dropdown

config/authorities/other_affiliation.yml
Added Office of Undergraduate Research (OUR).
=> Added Office of Undergraduate Research (OUR).

app/mailers/scholars_archive/container_mailer.rb, app/views/scholars_archive/container_mailer/report_email.html.erb, lib/tasks/filesets_inventory_check.rake, spec/mailers/scholars_archive/container_mailer_spec.rb
`UPDATE:` Make an update based on the feedback from the other PR on the `fileset_inventory_check`.
=> Update on FileSets Inventory Check

app/controllers/hyrax/my/works_controller.rb
=> fixes add to collection on page 2 error

lib/tasks/filesets_inventory_check.rake
`UPDATE:` Fix the header to only display at the top of the CSV file.
=> Fix the header for Filesets

app/models/hyrax/statistic.rb
If this works well for SA@OSU we should port to OD
=> Fix dashboard statistics speed

app/controllers/catalog_controller.rb
=> Replace Solr Local Params with regular params in linked searches

app/mailers/scholars_archive/container_mailer.rb, lib/tasks/filesets_inventory_check.rake
`BUG FIX:` Add in fix to handle of error exception when it ran through the script to handle bad files.
=> Add in fix to the inventory check

config/authorities/other_affiliation.yml
=> Update other_affiliation.yml - add Fall Virtual Symposium

app/assets/stylesheets/osu.scss, app/views/records/edit_fields/_geo_section.html.erb, app/views/scholars_archive/base/_geo_bbox.html.erb, app/views/scholars_archive/base/_geo_point.html.erb, app/views/scholars_archive/base/_nested_geo_bbox.html.erb, app/views/scholars_archive/base/_nested_geo_points.html.erb, spec/views/hyrax/admin/workflows/index.html.erb_spec.rb
`IN PROGRESS:` Replace the `remove` button with the `trash can icon` instead of the text display the `remove` in the geo section.
=> Revise the 'remove' button in geo section

app/assets/stylesheets/osu.scss, app/views/scholars_archive/base/_geo_bbox.html.erb, app/views/scholars_archive/base/_geo_point.html.erb
`BUG FIX`: Fix the web layout of the `bbox_nested`.
=> Add fix to the layout of geoname

app/models/solr_document.rb, app/presenters/concerns/scholars_archive/default_presenter_behavior.rb, app/views/hyrax/base/_attribute_rows.html.erb, app/workers/fetch_graph_worker.rb, lib/scholars_archive/attributes_list.rb
`BUG:` Fix the location display on show page
=> Fix the location display on show page

app/helpers/hyrax/file_set_helper.rb, app/views/hyrax/file_sets/_actions.html.erb, app/views/hyrax/file_sets/_form.html.erb, app/views/hyrax/file_sets/edit.html.erb, config/locales/hyrax.en.yml
`BUG:` Add in `FileSet` edit to be able to edit the URL on there rather than the work edit page.
=> Add in file_set edit from show page

app/services/scholars_archive/label_parser_service.rb
`UPDATE:` Modify the function of the parser to make sure the label parse correct value.
=> Modify the parser a bit for geoname

config/locales/simple_form.en.yml
`UPDATE:` Add in new hint message to the `ext_relation`
=> Update the help hint on ext relation

config/authorities/other_affiliation.yml
=> URSA Update other_affiliation.yml

lib/tasks/filesets_inventory_check.rake
`UPDATE:` Make an adjustment to the `task` to handle error for the foreign character.
=> Add in an error check for some ASCII conversion to foreign characters

app/views/hyrax/base/_items.html.erb
`BUG:` Fix the display problem of FileSet not showing up if there are more than one FileSet.
=> Update bug on coding for ext_relation

.rubocop_fix_me.yml, spec/views/hyrax/base/_items.html.erb_spec.rb
`TEST:` Update the `_items` test to test out the list item for FileSet is in there.
=> Create a test to make sure HTML render the correct fileset layout

lib/tasks/filesets_inventory_check.rake
`UPDATE:` Make a small change to the fileset `rake task` with encoding.
=> Update fileset encoding string

app/mailers/scholars_archive/container_mailer.rb, lib/tasks/filesets_inventory_check.rake
`UPDATE:` Add code to zip file and reduce down file size and attach it to email.
=> Add in zip content to filesets inventory

.circleci/config.yml
Update to newer remote docker image, old one was EOL.
=> Update remote docker

app/forms/concerns/scholars_archive/dataset_terms.rb
`BUGS:` Add in a fix to let the `funding_body` to be added in and pass on saving or approving `Dataset`.
fixes #2703
=> Update the forms to include funding_body

config/authorities/accessibility_feature.yml
`BUGS:` Add a fix to a small typo in the YAML file.
=> Fix a typo mistake in YAML file

app/controllers/scholars_archive/accessibility_request_form_controller.rb, app/models/scholars_archive/accessibility_request_form.rb, app/views/scholars_archive/accessibility_request_form/new.html.erb, config/locales/hyrax.en.yml
`FEATURE:` Add in a confirm email field to double check on email sending.
=> Add in a confirm email field

app/assets/stylesheets/osu_settings.scss
`UPDATE:` Add new CSS color to `osu-orange`
=> Update CSS to the new osu-orange

app/assets/javascripts/add_date_field.js.coffee, app/assets/javascripts/add_geo_field.js.coffee, app/assets/javascripts/embargo_date_field.js, app/assets/javascripts/embargo_reason_field.js, app/assets/javascripts/field_other.js.coffee, app/assets/javascripts/nested_field.js.coffee, app/assets/javascripts/ordered_creator.js, app/assets/stylesheets/osu.scss, app/inputs/multi_value_label_url_input.rb, app/inputs/multi_value_ordered_input.rb, app/inputs/multi_value_select_other_input.rb, app/views/hyrax/base/_form_permission_embargo.html.erb, app/views/hyrax/base/_form_progress.html.erb, app/views/hyrax/base/_form_relationships.html.erb, app/views/hyrax/base/_form_visibility_component.html.erb, app/views/records/edit_fields/_keyword.html.erb, spec/views/records/edit_fields/_degree_field.html.erb_spec.rb, spec/views/records/edit_fields/_degree_name.html.erb_spec.rb
=> Edit dropdown and nested form element fixes

lib/qa/authorities/academic_affiliation.rb
`UPDATE:` Update code to fetch from `URL`
=> Update the method in authorities for AcademicUnit

app/indexers/scholars_archive/file_set_indexer.rb
`BUG:` Add in more solr field for `ext_relation` in FileSet.
=> Update the FileSet indexer to add in couple more field to Solr

app/assets/stylesheets/osu.scss, lib/qa/authorities/academic_affiliation.rb
`UDPATE:` Make adjustment in display and spacing based off of feedback.
=> Modify the display of controlled vocab on Academic Unit

lib/qa/authorities/academic_affiliation.rb
`BUG:` Fix the label display in `ingest_form` where the URL is display in the `Academic Unit`.
=> Modify the parsing label on Academic Unit

lib/qa/authorities/academic_affiliation.rb
Reverts osulp/Scholars-Archive#2781
=> Revert "Modify the parsing label on Academic Unit"

lib/scholars_archive/controlled_vocabularies/research_organization_registry.rb
`BUG:` Update the fetch graph with HTTPS for `funding_body`
=> Create URL via HTTPS rather than HTTP
