app/views/homepage/_home_header.html.erb
config/locales/en.yml
spec/views/homepage/_home_header.html.erb_spec.rb

Fixes #49 Adds the button in for non admins to browse currently added 'things'. If we need to change any of the vocabulary used on the buttons, that is a quick and easy change.

Added button to home header for browsing ingested 'things'

---

app/assets/javascripts/hydra-editor/manage_repeating_fields.js

Fixes #159
This adds a remove button to the last element of a group of fields under a certain metadata field. 
1)When the form is first visited, the last field will only have the add button
2)When removing a field not at the bottom of the list, it keeps both buttons on the last field
3)When removing the field at the bottom, it adds the add and remove buttons to the field above it.
4)When adding a field, the add button will move to the newly created field with a remove button.

Added add and remove buttons where needed

---

Gemfile.lock
app/helpers/sufia_helper.rb
lib/scholars_archive/uri_enabled_string_field.rb
spec/features/edit_batch_spec.rb
spec/lib/scholars_archive/uri_enabled_string_field_spec.rb

Fixes #302 Sadly, most of the time an array of multiple different labels gets returned on the show page and in the form. Now, instead of using the first option which may not be the english label, we are now using the uri and its preferred label after it is cast to a triple powered resource. This should guarantee the label we have to always be the preferred language which is english.

Using Preferred label on show page and in form

---

config/application.rb
config/environments/development.rb
config/environments/test.rb

I was getting an error that saying 'undefined method web console'. I figured we didnt need it for production, so I moved the config to the test and dev environments.

Add web console config to environment

---

Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.css
app/forms/curation_concerns/generic_work_form.rb
app/models/generic_work.rb
app/views/records/edit_fields/_based_near.html.erb
app/views/records/edit_fields/_default.html.erb
app/views/records/edit_fields/_subject.html.erb
config/application.rb
config/initializers/simple_form_triple_powered_properties.rb
lib/assets/javascripts/triple_powered_properties.js
lib/assets/javascripts/triple_powered_properties/button.es6
lib/assets/javascripts/triple_powered_properties/control.es6
lib/assets/stylesheets/triple_powered_properties.scss
lib/scholars_archive/triple_powered_properties/errors.rb
lib/scholars_archive/triple_powered_properties/forms/work_form.rb
lib/scholars_archive/triple_powered_properties/has_url_validator.rb
lib/scholars_archive/triple_powered_properties/inputs/triple_powered_property_input.rb
lib/scholars_archive/triple_powered_properties/triplestore.rb
lib/scholars_archive/triple_powered_properties/work_behavior.rb
lib/scholars_archive/triple_powered_properties/work_indexer.rb
lib/tasks/scholars_archive.rake
spec/rails_helper.rb
spec/scholars_archive/triple_powered_properties/work_behavior_spec.rb
spec/scholars_archive/triple_powered_properties/work_indexer_spec.rb

A simple approach for connecting properties with URI's to fetch the graph and use the label(s) defined for them. "URI Enabled Fields" as it is known..
fixes #361 
fixes #367 
fixes #444

TriplePoweredProperties

---

config/initializers/hyrax.rb

Fixes #541 
Geonames is configured in the application now. Also, the Geonames credentials exist in LastPass and Geonames account is set up such that the free webapp service is working. This allows the location field to autocomplete in scholars archive.

Configure Geonames username in app. Geonames search working

---

config/initializers/legato.rb

fix #551 
The setting of GA profile is in config/analytics.yml on shared dir, and Google console with project_id scholarsarchive-165716

preload legato library for non-production env

---

Gemfile
Gemfile.lock
app/forms/hyrax/default_work_form.rb
app/models/default_work.rb
app/models/etd.rb
config/application.rb
config/triplestore_adapter/blazegraph/blazegraph.properties
config/triplestore_adapter/blazegraph/log4j.properties
lib/scholars_archive/triple_powered_properties/errors.rb
lib/scholars_archive/triple_powered_properties/has_url_validator.rb
lib/scholars_archive/triple_powered_properties/inputs/triple_powered_property_input.rb
lib/scholars_archive/triple_powered_properties/triple_powered_form.rb
lib/scholars_archive/triple_powered_properties/triplestore.rb
lib/scholars_archive/triple_powered_properties/work_behavior.rb
lib/scholars_archive/triple_powered_properties/work_indexer.rb
spec/rails_helper.rb
spec/scholars_archive/triple_powered_properties/triple_powered_form_spec.rb
spec/scholars_archive/triple_powered_properties/triplestore_spec.rb
spec/scholars_archive/triple_powered_properties/work_behavior_spec.rb
spec/scholars_archive/triple_powered_properties/work_indexer_spec.rb

Fixes #552 
This adds all the necessary work to have blazegraph as a triplestore backend. It fetches and caches and accepts URI's and indexes the labels in solr.

Blazegraph enabled for Scholars Archive

---

app/actors/scholars_archive/actors/add_other_field_option_actor.rb
app/assets/javascripts/application.js
app/assets/javascripts/degree_other.js.coffee
app/controllers/concerns/scholars_archive/works_controller_behavior.rb
app/forms/scholars_archive/etd_work_form_behavior.rb
app/models/concerns/scholars_archive/etd_metadata.rb
app/models/other_option.rb
app/services/scholars_archive/default_middleware_stack.rb
app/views/records/edit_fields/_degree_field.html.erb
app/views/records/edit_fields/_degree_level.html.erb
config/application.rb
config/authorities/degree_field.yml
db/migrate/20170714202009_create_other_options.rb
db/schema.rb
spec/actors/scholars_archive/add_other_field_option_actor_spec.rb
spec/models/other_option_spec.rb
spec/views/records/edit_fields/_degree_field.html.erb_spec.rb
spec/views/records/edit_fields/_degree_level.html.erb_spec.rb

- Added add_other js and updated the form partials to allow the user to enter custom values when selecting "Other" for "degree_field" and "degree_level": fixes #719
- Implemented the `ScholarsArchive::Actors::AddOtherFieldOptionActor` that is used to persist "other" values provided by the user in the form into the `OtherOption` table: closes #727

added other input for degree_field and degree_level select

---

app/services/scholars_archive/workflow/changes_required_notification.rb
app/services/scholars_archive/workflow/deposit_received_notification.rb
app/services/scholars_archive/workflow/deposited_notification.rb
app/services/scholars_archive/workflow/pending_review_notification.rb
config/workflows/datasets.json
config/workflows/gtd.json
config/workflows/one_step.json
config/workflows/stakeholder.json

- Updated `ChangesRequiredNotification` and `DepositReceivedNotification` to send to the user who initiated deposit only
- Updated `PendingReviewNotification` to send the emails to the approving role only (the user who made the deposit should get the `DepositReceivedNotification` email instead)
- Added diagrams for One Step and Graduate Thesis and Dissertation Workflows: https://github.com/osulp/Scholars-Archive/wiki/Workflows

set proper recipients in workflow configs and email notification objects

---

app/services/scholars_archive/academic_units_service.rb
app/services/scholars_archive/degree_field_service.rb
app/services/scholars_archive/degree_level_service.rb
app/services/scholars_archive/language_service.rb
app/services/scholars_archive/license_service.rb
app/services/scholars_archive/peerreviewed_service.rb
app/views/records/edit_fields/_academic_affiliation.html.erb
app/views/records/edit_fields/_degree_field.html.erb
app/views/records/edit_fields/_degree_level.html.erb
app/views/records/edit_fields/_language.html.erb
app/views/records/edit_fields/_license.html.erb
app/views/records/edit_fields/_peerreviewed.html.erb
spec/views/records/edit_fields/_degree_level.html.erb_spec.rb

Updated dropdown options in the following fields to display all options available (active and inactive for admin users)
- academic_affiliation
- degree_field
- degree_level
- language
- license
- peerreviewed
fixes #733

updated select inputs to display all options for admin users

---

app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/views/catalog/_date_decades_facet.html.erb

Blacklight currently supports only two types of sorting in a facet_field: `index` (ascending alpha)  and `count` (hits per item), see https://github.com/projectblacklight/blacklight/wiki/Configuration---Facet-Fields
However, it allows us to render a partial for a facet_field where we have access to `display_facet.items` that holds all the facet results that can be sorted as needed before the pagination is set. With this approach, added the partial `app/views/catalog/date_decades_facet`, which uses the `facet_desc_sort!` helper to apply the custom sorting. 
fixes #701

added facet partial for date_decades to render custom desc sorting

---

app/views/hyrax/admin/workflows/index.html.erb
config/initializers/hyrax_status_list_service_hack.rb

With just greg's fix, the lists weren't filtering. So I had to figure out some way to filter the lists out. This allows the lists to be filtered but in the view. The other place to filter this would be here. https://github.com/samvera/hyrax/blob/master/app/controllers/hyrax/admin/workflows_controller.rb#L17
However, @status_list is a status_list_service that has select as a private method. It makes it slightly difficult to filter out the proper objects. The only other way I could see it filtered is using the proper solr_query but that seems like a low level issue that we chose to not look into right now. For now, I propose just filtering in the view and calling it a day. Ill make a ticket that describes the issue and make comments where necessary.

Default query and filter in view

---

config/workflows/gtd.json

items were getting stuck in Pending Review state. Removed Request Review action and replaced it with Restart Review Process action that takes item back to Graduate School Review state

update GTD workflow so that items don't get stuck

---

app/views/hyrax/homepage/_featured_fields.html.erb

updated keywords row on featured pane to use `featured.subject` instead of `featured.keyword` and set empty string for no results
fixes #909

updated featured fields to use subject instead of keyword

---

config/deploy/production.rb
config/deploy/staging.rb

It looks like we can restart processes with `sudo /usr/bin/monit restart all`. This would allow us to restart existing puma and sidekiq processes on deploy, ref #914

add monit restart after deploy:published hook

---

app/services/scholars_archive/triple_powered_service.rb

fixes #938 
It turns out that we were sending the error to the logs, but we were not returning `nil`, which is the expected behavior when retrieving labels and the graph is not available (see https://github.com/osulp/Scholars-Archive/blob/master/app/services/scholars_archive/triple_powered_service.rb#L65)
I found that sending the error to rails logger returned `true` by default, which ended up causing the query to fail on `ScholarsArchive::TriplePoweredService.predicate_labels(graph)` (see https://github.com/osulp/Scholars-Archive/blob/master/app/services/scholars_archive/triple_powered_service.rb#L70)

return nil after sending error message to logs

---

app/views/_head_tag_extras.html.erb

Create head_tag_extras partial to load Open Sans font.

---

config/fedora.yml
config/initializers/active_fedora_timeout_monkey_patch.rb

- added note to remove monkey patch when active_fedora pr 1271 is released
- updated patch to override the connection options only

added todo note and updated active_fedora_timeout_monkey_patch

---

app/indexers/default_work_indexer.rb

fixes #973 
- It looks like we were fetching only the top label with `fetch_top_label` which works for single value fields. 
- Added `fetch_all_labels` (instead of `fetch_top_label`) to get an array of label entries instead for multi-value fields like`other_affiliation`

fetch all labels for mult-value fields

---

app/controllers/catalog_controller.rb
app/models/concerns/scholars_archive/default_metadata.rb

this update exposes `dspace_collection` and `dspace_community` as search fields so that we can search the catalog as follows:
```
localhost:3000/catalog?q=hello+world&search_field=dspace_collection
```
references #1015

Redirec handle to solrquery

---

app/views/shared/_citations.html.erb

fixes #1108 
- added the logic to render a date for `citation_publication_date`. 
- for `citation_pdf_url`, we used the `representative_id` to check when there is file sets listed as members. If `representative_id` is not set, then we iterate over the `member_presenters` to get the member (child work) download url.
- expose `citation_journal_title`, `citation_volume`, `citation_issue` if the work is an article

added custom citations partial for google scholar

---

app/controllers/application_controller.rb
app/views/shared/_citations.html.erb

- fixes a bug on the show page view that fails to generate a `download_url` for `citation_pdf_url` (used for Google Scholar) when a `representative_id` is not set and the only member or first member in the list is a `FileSet`
- added an update to process default_url_options with https on production only

added fix to generate citation pdf urls for child filesets

---

app/assets/stylesheets/osu.scss
app/views/_logo.html.erb

Fixes #1126 
Fixes #1127 
Reduced left margin on OSU logo.
Added left padding to ScholarsArchive@OSU to match the logo and other elements.
Changed .dashboard masthead to have position:relative to match main layout. This also uncovered the lower-masthead-border-banner and fixed the overhang on the little menu collapse arrow and the Edit Work sidebar.
Changed OSU logo link to be https://oregonstate.edu

Adjust margins and fix Admin layout.

---

app/forms/scholars_archive/dataset_form_behavior.rb
app/views/hyrax/base/_form_metadata.html.erb

Fixes #1159 
Also copy in updated _form_metadata.html.erb changes from Hyrax, which doesn't show 'Additional Fields' if there are no secondary terms in a form.

Move Dataset form fields above fold.

---

app/assets/stylesheets/osu.scss

Fixes #1182 
Showing same CSS change:

Add CSS to use smaller facet label size.

---

app/assets/javascripts/tooltips.js
app/renderers/hyrax/renderers/search_and_external_link_attribute_renderer.rb
spec/renderers/hyrax/renderers/scholars_archive_nested_attribute_renderer_spec.rb
spec/renderers/hyrax/renderers/search_and_external_link_attribute_renderer_spec.rb

fixes #1144 
Fixes a typo, but the mis-typed class name isn't desired anyhow (it gives a bad looking style otherwise)

tooltips for internal/external links and a little bugfix

---

app/forms/scholars_archive/article_work_form_behavior.rb

Remove conference fields from secondary terms.

---

app/views/hyrax/base/_form_progress.html.erb

added admin check `!current_user.admin?` (user not an admin) in the form progress (default value for `work_requires_files` is true), so the view should skip the file requirement if the user is not an admin:
`<% if Hyrax.config.work_requires_files? && !current_user.admin? %>`

allow creating works without files for admin users

---

sa_scripts/fix_work_visibility.rake

fixes #1243 
This script sets the proper visibility of a work based on the existing embargo and double checks that the visibility matches the `visibility_during_embargo` and `visibility_after_embargo` properties.
Cleanup report for the cleanup:
https://docs.google.com/spreadsheets/d/1dZdCadsJ4OsZ94dj19xnlvs4Y8DFXV12sLe5nySLSKY/edit?usp=sharing

add task to update a given list of works and set their proper visibility

---

lib/tasks/embargo_state.rake

closes #1248 
- This task can be used to generate a CSV report to retrieve current embargo values (work_visibility, embargo_release_date, visibility_during_embargo, visibility_after_embargo, embargo_history) for existing works in hyrax given a list of handles with data from dspace. 
- The output CSV file contains embargo info for the member/file sets in addition to the parent work. These are identified based on the bitstream name in dspace. 
- The CSV file also includes columns with values in dspace (dspace_handle, dspace_embargo_date, dspace_visibility) and are included to verify that the embargo values were migrated properly.
**Usage**:
```
RAILS_ENV=production bundle exec rake scholars_archive:embargo_state
```
**Input**:
The task expects an input file …

script to verify current embargo state values in a given list of works

---

app/controllers/concerns/scholars_archive/my_shares_behavior.rb
app/controllers/scholars_archive/shares_controller.rb
config/routes.rb

fixes #1283 
- We are adding a Scholars Archive behavior for `SharesController`, which includes `custom_redirect`
- `custom_redirect` could be used to prevent a template-not-found error for `dashboard/shares` path for now (We are redirecting from `dashboard/shares` to `dashboard/my/works`, which is the default path for regular users)
- A related issue has been reported in hyrax here https://github.com/samvera/hyrax/issues/2767
- Once hyrax/issues/2767 is resolved, we can remove the `custom_redirect` and `ScholarsArchive::MySharesBehavior` as well if not needed in the end

added scholars archive shares behavior to handle template not found

---

lib/tasks/bulk_update_csv.rake

sometimes a trailing space on the data in the repository can cause grief for processing bulk updates.. this makes the `include?` a little more liberal at the value level of each row
fixes #1308

makes bulk update a little more liberal for finding a row

---

app/assets/stylesheets/osu.scss

ref #1311 (not fully addressed throughout the application)
This sets the link color, for the work type modal help text, to osu orange until #1311 is solved throughout the application.

sets link text to an identifiable color for the help text

---

app/forms/scholars_archive/default_work_form_behavior.rb
spec/forms/hyrax/administrative_report_or_publication_form_spec.rb
spec/forms/hyrax/article_form_spec.rb
spec/forms/hyrax/conference_proceedings_or_journal_form_spec.rb
spec/forms/hyrax/dataset_form_spec.rb
spec/forms/hyrax/default_form_spec.rb
spec/forms/hyrax/eesc_publication_form_spec.rb
spec/forms/hyrax/graduate_project_form_spec.rb
spec/forms/hyrax/graduate_thesis_or_dissertation_form_spec.rb
spec/forms/hyrax/open_educational_resource_form_spec.rb
spec/forms/hyrax/purchased_e_resource_form_spec.rb
spec/forms/hyrax/technical_report_form_spec.rb
spec/forms/hyrax/undergraduate_thesis_or_project_form_spec.rb
spec/views/hyrax/base/_form_instructions_spec.rb

Fixes #1157 
This adds hidden fields to the end if a user is an admin. Since it lives on default it will show up on all the work types.

Adds hidden values to the end for admin users.

---

app/actors/scholars_archive/actors/add_other_field_option_actor.rb
app/models/default.rb
app/services/scholars_archive/field_validation_service.rb
lib/scholars_archive/validators/other_option_degree_validator.rb
spec/views/hyrax/base/_form_instructions_spec.rb
spec/views/hyrax/base/_work_description.erb_spec.rb

fixes #1332 
Created `FieldValidationService` to handle validation for `Other` values provided for degree fields (degree_field, degree_name, degree_level, degree_grantors) so that it can be used both in the actor `add_other_field_option_actor` and the form validator `other_option_degree_validator`.
The service also takes care of the validation logic and checks if it's an etd or non-etd (i.e. `Default`) and assigns the proper validation.
related: #1301

added field_validation_service

---

config/initializers/hyrax_status_list_service_hack.rb

fixes a bug in the review queue related to admin_set_id changing to source_id in hyrax 2.1.0. Searched the code base for other references to admin_set_id and didn't find any.

fixes bug with 2.1.0 changing to source_id

---

app/views/catalog/facet.html.erb

Facet pagination is a very slow partial, SA is not displaying the "header" pagination so it shouldn't be rendered (and cause the _facet_pagination partial to slowly render again)

override blacklights facet partial to prevent the double rendering of facet_pagination

---

app/views/catalog/_search_form.html.erb

Add :page to except method to exclude from Advanced Search link.

---

app/indexers/default_work_indexer.rb

Fixes #1467 
Adds back in the multiple? check and iterates over values to call top_label on each one.

For properties with multiple, get top label of each URI.

---

.github/ISSUE_TEMPLATE.md

removed #rationale section because i've always hated that part as it seems duplicative of the Descriptive Summary section

modified template to remove extraneous info

---

app/models/concerns/scholars_archive/default_metadata.rb
app/models/nested_ordered_creator.rb
spec/models/default_spec.rb
spec/models/nested_ordered_creator_spec.rb

fixes #1544 
usage:
```
> d = Default.new(title:["test"],nested_ordered_creator_attributes:[{index:"0", creator:"Greg Luis"}]).save
> d.nested_ordered_creator.first.id
=> "http://fcrepo:8080/rest/dev/vx/02/1f/08/vx021f082#nested_ordered_creatorg47002074968760"
> d.nested_ordered_creator.first.index
=> ["0"]
> d.nested_ordered_creator.first.creator
=> ["Greg Luis"]
```

added NestedOrderedCreator model

---

app/models/concerns/scholars_archive/default_metadata.rb
spec/models/default_spec.rb

fixes #1564 
This will allow us to reject partially empty items (i.e. items with an index but without a creator and vice versa).
It should still reject the items when all of them are empty (excluding items where the destroy flag is turned on).

updated ordered creator model to reject empty items

---

app/assets/javascripts/tooltips.js

Expand more info tooltip to look for links starting with http
Could tweak further to better disambiguate between internal (other related items) or external links and provide different messages.

Expand more info tooltip to include links starting with http

---

app/assets/stylesheets/osu.scss

Fixes #1522 
40% width is pretty arbitrary, but large enough to handle longer email addresses in the box but not too big when screen size is smaller.
Should target both User Collections (Sharing) and Admin Sets (Participants).

Reduce size of Add User lookup field.

---

app/assets/javascripts/nested_field.js.coffee

@straleyb It looks like not all the ids were being identified when adding, removing, and resetting items because of the new element (textarea) introduced for description and abstracts, but this update should take care of these cases.

updated selector in nested_field js to reset textarea elements

---

app/assets/javascripts/ordered_creator.js
app/models/concerns/scholars_archive/has_nested_ordered_properties.rb
app/models/solr_document.rb
spec/models/default_spec.rb

- Added support to legacy methods for `abstract`, and `contributor` on work models
- Fixed spelling issue with nested related items

added support to legacy model methods for new fields

---

app/controllers/catalog_controller.rb

Advanced search still works with sorted fields. Just needed to update what fields showed up in the advanced search field
Fixes #1649

update fields for advanced search

---

config/locales/hyrax.en.yml

Fixes
https://github.com/osulp/Scholars-Archive/issues/1684
It looks like we can set labels for custom field names used for query searching.
The trick is to define it right below search > fields
https://github.com/projectblacklight/blacklight/blob/v6.15.0/config/locales/blacklight.en.yml#L212

added proper labels to search facets and tag

---

config/initializers/sidekiq.rb

A recent update of Sidekiq (or Rails?) caused the delete and retry functionality to stop working a return an HTTP 403 Forbidden. This has fixed it, but will require a modification for Rails >= 5.2 eventually.
https://github.com/mperham/sidekiq/issues/2560

fixes Sidekiq administration functions

---

app/forms/hyrax/forms/batch_upload_form.rb
app/models/concerns/scholars_archive/has_nested_ordered_properties.rb
config/initializers/batch_create_job_hack.rb

fixes #1689 
- updated `batch_upload_form` to include missing ordered attributes
- added override for `BatchCreateJob` to set `nested_ordered_title_attributes` hash so that it is also based on the filename like `title`.

Fix batch upload forms with nested fields

---

app/assets/javascripts/hyrax/browse_everything.js

fixes #1691 
After looking in the `browse-everything` gem examples section, it looks like we can load it on the document to fix the error: https://github.com/samvera/browse-everything/blob/v0.15.1/spec/support/app/views/file_handler/main.html.erb#L16

updated browse_everything JS

---

lib/scholars_archive/migrate_ordered_metadata_service.rb

- created dev instance based on current revision in production and tested `has_migrated?`
- added additional logs (solr, fedora, and csv values) when assigning new ordered attributes 
- fixed minor issues for the index property
- reset ordered fields before assigning new ordered values (some fields like `creator` , `contributor`, `additional_information`, and `related_items`) are will be inheriting the same predicates from unordered fields

qa for has_migrated? method

---

app/controllers/concerns/scholars_archive/works_controller_behavior.rb

Doesn't try to operate in the same context as the work type that is set by the controller, the migration code doesn't have anything that cares about work-type in this regard. So, in-place migration just queries the work, does the migration if necessary, and gets out of the way for the controller to do what it would naturally do.

fixes in-place migration to use AF::Base

---

app/views/hyrax/base/_form_progress.html.erb

fixes #1700 
rebased progress form to get the following updates introduced in hyrax 2.3.0:
- removed cancel button
- added another FlipFlop.show_deposit_agreement check
- added progress bar for immediate feedback after the form is submitted
see screenshots:

rebase _form_progress.html.erb to get updates for hyrax 2.3.0

---

app/controllers/catalog_controller.rb

This fixes title search. Full title search with and without quotes works as expected on local dev instance.
Also changed sort by title field.
Fixes #1707

Update title field references to nested_ordered_title_label.

---

app/forms/scholars_archive/dataset_form_behavior.rb

fixes #1710 
We missed permitting the new ordered fields in the dataset form behavior.  This update enables new changes in the form to be persisted.

permit ordered fields in dataset form behavior

---

app/views/hyrax/homepage/_featured_fields.html.erb
app/views/hyrax/homepage/_recent_document.html.erb
config/locales/hyrax.en.yml

Limited display of creators and subjects to 5.
Also changed labels to singular form to match the attribute display on a work show page.
Related to #1012 
Featured Works:
Recently Uploaded:

For Featured Works and Recent Documents on homepage, change Depositor to Creator

---

app/models/solr_document.rb

fixes https://github.com/osulp/Scholars-Archive/issues/1709
It looks like this is happening for fields that contain only one empty string in the value like the case with `conference_name = [""]` 
For some reason, when the renderer checks for blank values, it doesn't hide it because `[""].blank?` evaluates to false instead of true. The renderer expects this to evaluate to true to hide the field: https://github.com/samvera/hyrax/blob/v2.3.0/app/renderers/hyrax/renderers/attribute_renderer.rb#L40
This update cleans empty strings so we get `[]` instead of `[""]` for the presenter/attribute renderers.

update solr doc to exclude empty strings

---

sa_scripts/migrate_ordered_metadata.rake

fixes #1728 
added rake task `bundle exec rake scholars_archive: force_migrate_ordered_metadata` to restart migration on works that were partially migrated (title and abstract were successfully migrated for a set of works): https://docs.google.com/spreadsheets/d/13KT0IpDcjzqJu_IC3kLO_smaFpqzN2csRp_21i4Gz0c/edit#gid=1126555583
This forces migration on creator, contributor and additional_information fields

added force_migrate_ordered_metadata task

---

app/models/collection.rb

fixes #1735
- It turns out that hyrax now has a separate indexer for the Collection model. See the new collection template: https://github.com/samvera/hyrax/blob/v2.3.0/lib/generators/hyrax/templates/app/models/collection.rb#L6
- The metadata for collections in the template is now based on https://github.com/samvera/hyrax/blob/v2.3.0/app/models/concerns/hyrax/basic_metadata.rb

added missing indexer to collection model

---

.gitignore
app/controllers/catalog_controller.rb
app/models/concerns/scholars_archive/has_solr_labels.rb

Fixes #1745 
This indexes creators on the creator_ssim index field that are unindexed and unique. This is to resolve the issue of duplicate creator labels based on different ordering. Since facets dont need any concept of order, removing the order and just indexing labels allows for the paring down of the length of results and should allow for the searching of creators again.

Uses creator_sim for facets

---

app/controllers/concerns/scholars_archive/works_controller_behavior.rb
config/initializers/work_migrator.rb
config/local_env.example.yml

fixes #1760 
I feel like leaving the migration service allows us to use it, in isolation, if we had to process something in particular.

disables in-place migration since it is finished

---

app/services/scholars_archive/all_facet_values_service.rb

fixes #1794 
We can reproduce the server error in the console with:
```
c = RSolr.connect(url: ActiveFedora.solr_config[:url])
p = {:rows=>0, :facet=>"on", "facet.field"=>"creator_sim", "facet.limit"=>100000, "f.creator_sim.facet.limit"=>100000}
r = c.get 'select', params: p
all_facets = r['facet_counts']['facet_fields']['creator_sim']
irb(main):005:0> Hash[*all_facets]
Traceback (most recent call last):
8: from bin/rails:4:in `<main>'
7: from bin/rails:4:in `require'
6: from /data0/hydra/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'
5: from /data0/hydra/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
4: from /data0/hydra/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands/comma …
```

updated solr_facets to fix server error

---

lib/tasks/bulk_update_csv.rake

When the value of `property = work["has_journal"]` is blank, it defaults to a multi-value field that leads to a an ArgumentError:
```
ArgumentError: You attempted to set the property `has_journal' of nk322d32h to an enumerable value. However, this property is declared as singular.
/usr/local/bundle/gems/active-fedora-11.5.2/lib/active_fedora/attributes/property_builder.rb:49:in `has_journal='
/usr/local/bundle/gems/active-fedora-11.5.2/lib/active_fedora/attributes.rb:46:in `[]='
/data/lib/tasks/bulk_update_csv.rake:72:in `update_property'
/data/lib/tasks/bulk_update_csv.rake:47:in `update_work'
/data/lib/tasks/bulk_update_csv.rake:41:in `block in process_csv'
/data/lib/tasks/bulk_update_csv.rake:40:in `process_csv'
/data/lib/tasks/bulk_update_csv.rake:29:in `block (2 levels) in <top …
```

update bulk update script - check for single value properties

---

lib/tasks/migrate_works_10_or_more_items.rake

Task to query Solr to get works with handles where a given field (i.e. creator) has 10 or more items, and generate a csv file containing `id`, `has_morel_ssim`, and field count.
Usage:
```
bundle exec rake scholars_archive:migrated_works_10_or_more_creator
bundle exec rake scholars_archive:migrated_works_10_or_more_title
bundle exec rake scholars_archive:migrated_works_10_or_more_related_items
bundle exec rake scholars_archive:migrated_works_10_or_more_info
bundle exec rake scholars_archive:migrated_works_10_or_more_contributor
bundle exec rake scholars_archive:migrated_works_10_or_more_abstract
```
Output:
```
tmp/migrated_works_10_or_more_creator.csv
tmp/migrated_works_10_or_more_title.csv
tmp/migrated_works_10_or_more_related_items.csv
tmp/migrated_works_10_or_more_info.csv …
```

add task to query migrated works with 10 or more items in a given field

---

lib/tasks/bulk_update_csv.rake

fixes a bug with bulk update.. when the `to` field is empty the intention is to remove the value not set it to an empty string.
fixes related to #1797

bugfix for bulk updates to set field to nil instead of empty string

---

lib/scholars_archive/migrate_ordered_metadata_service.rb
lib/tasks/migrate_works_10_or_more_items.rake

- fixes sort bug in MigrateOrderedMetadataService
- adds `force_dspace_order_metadata_for_members` to cleanup creators in child members as well

Fix migrate ordered creators cleanup task

---

lib/tasks/migrate_works_10_or_more_items.rake

Related to https://github.com/osulp/Scholars-Archive/issues/1796 
Some works fixed manually have child works that still have unclean creators. My original tasks didn't take into account child works already fixed in https://github.com/osulp/Scholars-Archive/issues/1796#issuecomment-472152751 
This tasks gets a json file with handles, including child works that we can analyze 
```
"handle-url" => [{
member_id: "ABCDE", 
member_creators: {"hello","world"},
member_model: "articles"
}]
```
Update:
I'm also adding another task R3 to generate `r3_handles.csv` of handles with child works that we could run as `scholars_archive:migrate_dspace_creator_member_cleanup`

add task to get children from handles manually fixed

---

lib/tasks/migrate_works_10_or_more_items.rake

Related to #1796 
- QA task to check our work. The goal is to check both parents and members to see if we missed any in our previous tasks.
```
bundle exec rake scholars_archive:qa_for_unclean_creators
```
- Task to find child members in [Manual](https://docs.google.com/spreadsheets/d/1FRzgMpvlY27ylm1u3XdnRobvO5jNo64R2eu4x0kjgZw/edit#gid=0)
```
bundle exec rake scholars_archive:get_json_of_handles_manual_with_creators_and_children
```

add qa task to check our cleanup work on creators

---

.circleci/config.yml
lib/tasks/bulk_update_csv.rake

Implemented `remove_from_multivalue_row` to support the `-` operator (in the `from` column) and be able to remove specific items from a multi-value field with bulk updates.
Example input CSV:
```
id,from,to,property,
gm80hv32k,-,http://id.loc.gov/authorities/names/no2011160692,subject,
```
This will be helpful to be able to revert changes in combination with the `+` and replace items with the expected type in https://github.com/osulp/Scholars-Archive/issues/1825
Use case:
Input:
```
id,from,to,property,2046
gm80hv32k,-,http://id.loc.gov/authorities/names/no2011160692,subject,
gm80hv32k,+,Technical note (Forest Products Laboratory (U.S.)),subject,
```
Output:
```
Processing bulk update to works in csv: /data/tmp/bulk_edits/test_bulk_edits.csv
Article gm80hv32k subject row removed …
```

add support to remove items for multivalue fields in bulk updates

---

app/renderers/hyrax/renderers/search_and_external_link_attribute_renderer.rb

fixes issue when `publisher` is not a uri, so a uri escape is not required.
steps to reproduce the error:
1. set publisher
```
irb(main):002:0> publisher = "Corvallis, Or. : Agricultural Experiment Station. Oregon State College."
=> "Corvallis, Or. : Agricultural Experiment Station. Oregon State College."
```
2. escape special chars
```
irb(main):003:0> Addressable::URI.escape(publisher)
Traceback (most recent call last):
15: from bin/rails:4:in `<main>'
14: from bin/rails:4:in `require'
13: from /data0/hydra/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'
12: from /data0/hydra/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
11: from …
```

Fix invalid uri

---

lib/tasks/bulk_update_csv.rake

if the `to_value` is an empty string, then the overwrite value should be `nil`, not `[nil]`.

fix overwriting multivalue rows

---

app/helpers/application_helper.rb
app/views/hyrax/base/_form_visibility_component.html.erb
spec/views/hyrax/base/_form_progress.html.erb_spec.rb

fixes #1491 
It hides the `Oregon State University` and `Private` option under `Visibility` for the GraduateThesisOrDissertation model and non admin users only:

custom visibility options for depositors on GTD forms

---

app/actors/scholars_archive/actors/add_other_field_option_actor.rb
app/assets/javascripts/field_other.js.coffee
app/inputs/multi_value_select_other_input.rb

fixes https://github.com/osulp/Scholars-Archive/issues/1362
- Adds HTML5 validation on "Save" to 'Other value' inputs so that a form reload is not required when validating these custom elements.
- The update applies to degree_field, degree_name, degree_level, degree_grantors, other_affiliation

Add client side validation for custom elements

---

lib/tasks/bulk_ingest_csv.rake

This sets up the ability to create a work from a spreadsheet in the format of a CSV. The format is derived from this https://docs.google.com/spreadsheets/d/1jIEXGgSJTiXVis9y3Uu93bJtYsVnC6_TVHJsF2e-gGc/edit?pli=1#gid=261789307 and requires that all other permutations of ingest csv adhere to this style. 
Work still needing to be done:

Bulk ingest

---

config/initializers/noid_rails.rb

This is a hot fix to merge in a fix that's also provided upstream (https://github.com/MPLSFedResearch/cypripedium/pull/304/files) to cause AF to not get caught up with an LDP conflict

hotfix for LDP conflict fix

---

app/controllers/concerns/scholars_archive/download_analytics_behavior.rb
spec/controllers/scholars_archive/downloads_controller_spec.rb

Adds a rescue to Staccato.tracker call in Downloads controller behavior and sends error message and trace to the logs.

add rescue err to track_download

---

lib/tasks/bulk_update_csv.rake

- when given `*` under `from` and an empty cell under `to`, clear all values for given `property`
- this update applies to multi-value properties both ordered and unordered
- if given an unordered property (i.e. `additional_information`) check if value under `to` is present before proceeding with the update

allow to_value to be blank and clear all values

---

app/forms/hyrax/forms/batch_upload_form.rb
app/forms/scholars_archive/article_work_form_behavior.rb
app/forms/scholars_archive/default_work_form_behavior.rb
app/forms/scholars_archive/etd_work_form_behavior.rb
app/forms/scholars_archive/oer_work_form_behavior.rb
app/indexers/default_work_indexer.rb
app/indexers/etd_indexer.rb
app/models/concerns/scholars_archive/default_metadata.rb
app/models/concerns/scholars_archive/etd_metadata.rb
app/presenters/concerns/scholars_archive/default_presenter_behavior.rb
app/presenters/concerns/scholars_archive/etd_presenter_behavior.rb
spec/forms/hyrax/default_form_spec.rb

Move contributor_advisor field from ETD metadata to Default metadata.
Associated changes to update forms, indexers, models, presenters and
specs.
I haven't been able to test this locally, so this will need thorough QA, which I can help with.

Move Advisor to Default work type

---

app/helpers/google_scholar_helper.rb
app/services/scholars_archive/google_scholar_citation_service.rb
app/views/shared/_citations.html.erb
public/robots.txt
spec/services/scholars_archive/google_scholar_citation_service_spec.rb

Fixes https://github.com/osulp/Scholars-Archive/issues/1916
Google Scholar requires citation publication date meta tags to be in the format `Y/m/d` according to the indexing guidelines https://scholar.google.com/intl/en/scholar/inclusion.html#indexing.
- This update adds a `citation_publication_date` helper to format dates from the presenter to follow the guidelines. This one is used to format `date_uploaded`, which comes in the form `m/d/Y` and is a fallback when `date_created`, `date_issued`, and `date_accepted` are not available.
- It also skips empty or unsupported meta-tags like `citation_firstpage` and `citation_lastpage`.
- Robots.txt update: allow `catalog` to `Googlebot`
Notes/findings:

Google scholar citation updates

---

Dockerfile
lib/hyrax/controlled_vocabularies/location.rb
lib/qa/authorities/geonames.rb
lib/scholars_archive/feature_class_uri_to_label.rb

fixes #2016 
- It looks like we can fix location by switching to https like done in https://github.com/samvera/questioning_authority/pull/307 (it updates `lib/qa/authorities/geonames.rb`)
- `lib/qa/authorities/geonames.rb` is already overridden in ScholarsArchive, so applying the update on this file `geonames.rb` seems to work as well.

change protocol to https for geonames uris

---

app/indexers/default_work_indexer.rb

skip label assignment if it's empty to prevent server error.
This occurs when a resource comes back with no label, and the indexer tries to access it via `second` operation, resulting in a 500 error https://github.com/osulp/Scholars-Archive/issues/2016#issuecomment-575434644

fix 500 error on empty label values

---

lib/hyrax/controlled_vocabularies/location.rb
lib/qa/authorities/geonames.rb

FeatureClassUriToLabel stopped working as expected when testing https://github.com/osulp/Scholars-Archive/pull/2017 on staging.
This reverts some changes introduced in https://github.com/osulp/Scholars-Archive/pull/2017. It looks like https is only required in `parse_authority_response` (lib/qa/authorities/geonames.rb) and  `FeatureClassUriToLabel` (lib/scholars_archive/feature_class_uri_to_label.rb) to work properly, so the protocol doesn't have to be changed in the model properties for Location.
Staging:
On production:

update protocols to properly match FeatureClassUriToLabel

---

app/assets/stylesheets/osu.scss
app/views/hyrax/base/_tombstoned_work.html.erb

Fixes #2055
This should encapsulate the tombstone info much better. Citations now has a label too and word wrapping happens for text that is too long.

more refined view

---

app/controllers/concerns/scholars_archive/works_controller_behavior.rb

Reverts osulp/Scholars-Archive#2044
This is believed to introduce errors when a non-logged in user tries to view a show page:
I, [2020-07-07T11:18:40.607845 #18189]  INFO -- : [cd939825-06dd-42a6-ab20-9c9ca7d41ab3] method=GET path=/concern/graduate_thesis_or_dissertations/kd17ct94m format=html controller=Hyrax::GraduateThesisOrDissertationsController action=show status=500 error='NoMethodError: undefined method `username' for nil:NilClass' duration=336.49 view=0.00 db=12.22 params={"locale"=>"en"} time=2020-07-07 11:18:40 -0700

Revert "Feature/ability expanded"

---

.rubocop_fix_me.yml
app/models/ability.rb

Reverts osulp/Scholars-Archive#2095
This one needs more testing, so we could revert it for now. It seems to be causing file attachments to not work properly on production.

Revert "updates to allow admin to edit works (#2095)"

---

app/models/ability.rb

Reverts osulp/Scholars-Archive#2048
We can revert this one as well to resolve `undefined method `edit_users' for nil:NilClass`. When we are ready to push this update, we should also test for the anonymous user. This one is related to changes in PR https://github.com/osulp/Scholars-Archive/pull/2104

Revert "add edit ability to check if admin set of solr doc includes current user"

---

.rubocop_fix_me.yml
app/models/ability.rb

Reverts osulp/Scholars-Archive#2105
Updates:
- Bugfix for error found in production: `undefined method edit_users' for nil:NilClass`
- Merge with https://github.com/osulp/Scholars-Archive/pull/2095

Revert 2105 revert 2048 feature/allow editing if manager

---

app/controllers/concerns/scholars_archive/works_controller_behavior.rb

Reverts osulp/Scholars-Archive#2103
This PR also includes a bugfix for error found in production:
```
NoMethodError: undefined method `username' for nil:NilClass
```

Revert 2103 revert 2044 feature/ability expanded

---

app/views/hyrax/base/_tombstoned_work.html.erb

fixes #2055 
Html tweaks to the tombstone page so that elements align properly on the left side:

update tombstone page to fix alignment

---

app/workers/fetch_graph_worker.rb
lib/hyrax/controlled_vocabularies/location.rb
spec/workers/fetch_graph_worker_spec.rb

fixes https://github.com/osulp/Scholars-Archive/issues/1694
Location field updates:
- use commas as separator and remove extra spaces in location links
- update fetch graph worker to commit based_near_label to enable search and facets for location
Show page for location:
Search and facets for location:

update location links and enable search and facets

---

app/helpers/application_helper.rb
spec/views/hyrax/base/_form_progress.html.erb_spec.rb

fixes https://github.com/osulp/Scholars-Archive/issues/2113
Update forms for `HonorsCollegeThesis`, `GraduateProject`, and `UndergraduateThesisOrProject` models to remove both private and authenticated options and only keep public and embargo options.

update visibility options in forms

---

app/views/records/show_fields/_language.html.erb

Override hyrax language show field to use language label service

---

Gemfile
Gemfile.lock

There must be some kind of depedency on higher versions of mini_racer. Something to do with gcc or libV8

Pin mini_racer to 0.2.6

---

config/environments/staging.rb

Reverts osulp/Scholars-Archive#2165
Reverting until more testing can be done on staging, in order to deploy separate changes now.

Revert "Set harmony=true for uglifier to support es6"

---

app/workers/fetch_failed_graph_worker.rb
app/workers/fetch_graph_worker.rb

Fixes #2167
The problem came from pulling the solr document back out of solr. Any field that's not stored in solr (stored = false) can not be retrieved, so when we fetched the doc to update it we lost all stored fields including `creator_sim`.
This should also fix some missing metadata issues. Other fields that were likely lost because of this bug:
```
"title_sim",
"graduation_year_sim",
"creator_sim",
"degree_field_sim",
"degree_level_sim",
"degree_name_sim",
"language_sim",
"nested_ordered_creator_sim",
"nested_ordered_title_sim",
"peerreviewed_sim",
"publisher_sim",
"resource_type_sim",
"generic_type_sim",
"admin_set_sim",
"human_readable_type_sim",
"rights_statement_sim",
"license_sim"
```

Regenerate solr document in fetch graph workers to restore non-stored fields

---

app/controllers/catalog_controller.rb
app/models/concerns/scholars_archive/has_solr_labels.rb

Use the creator facet model for contributor in order to remove duplicate facet values from display. This was caused by the ordered information being part of the facet value on the backend but only the label being displayed on the frontend.
Fixes #2163 
As noted in #2163 to look for additional fields this could be happening to, this is the only facet remaining with this issue.
Needs #2177 to be fully effective.

Stop using nested ordered contributor field for facet

---

app/controllers/catalog_controller.rb
app/indexers/collection_indexer.rb
app/indexers/concerns/scholars_archive/indexes_combined_sort_date.rb
app/indexers/default_work_indexer.rb
app/models/collection.rb
solr/conf/schema.xml
solr/config/schema.xml

`title_ssi` is populated with the first ordered or unordered title, so that one should be reasonably similar behavior.
The system fields are generated by the actor stack and guaranteed to be on works, unlike `date_created` which is an optional field. `date_uploaded` is only applied to works, so collections get miss-sorted.
Reverts and Fixes #667

Replace sorting fields with system created dates and non-ordered titles

---

app/indexers/concerns/scholars_archive/indexes_combined_sort_date.rb

Ruby's safe navigation operator is great for pre-catching NoMethodError exception while traversing objects, but it only prevents calling a method on Nil. I previously understood it to also prevent exceptions when calling a method that doesn't exist

Fix misunderstanding of safe navigation operation and refactor grabbing sorting date

---

config/initializers/hacks/hydra_derivatives_processors_image_hack.rb

Flatten alpha channel in image derivatives to remove black backgrounds

---

config/initializers/hacks/hydra_derivatives_processors_image_hack.rb

Remove alpha channel in thumbnails instead of flattening it

---

lib/tasks/remove_abstract_and_title_data.rake

This prevents deletion of unordered titles if there are no ordered titles, and the same with abstract.
The thought is that the ordered titles/abstract will always be the complete and authoritative list of titles/abstracts, except only in the case that unordered exists and ordered do not exist.
That is to say, this does not check that the lists are similar in any way.
Fixes #1706

Add checks to not delete unordered titles/abstracts on works with only unordered values

---

app/controllers/catalog_controller.rb
app/indexers/default_work_indexer.rb

Once index is done, the catalog controller can be updated to use title_ssort
This is half of #1809
The second half can be finished once the reindex is finished

Prep for improved title sorting by indexing into title_ssort

---

config/authorities/degree_name.yml

Master of Science in Environmental Sciences (M.S.E.S.) is residual and not used in the system; MS in Environmental Sciences is the proper assignation. Also added DVM abbreviation.

Add Graduate Certificate plus cleanup

---

lib/tasks/bulk_ingest_csv.rake

fixes #2202 
I went with just setting `date_uploaded` on the work because I was unsure of the implications of using the actor stack and how that would interact with either creating our own Sipity entity or updating the one that would be created by an actor.

Add date_uploaded default value on bulk ingest

---

Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
app/models/solr_document.rb
config/routes.rb

This update removes our forked version of blacklight_oai_provider and replaces it with the official projectblacklight version. Are previous fork was forked by UNC and they have archived that repo in favor of projectblacklight.
Fixes #2231

Update blacklight_oai_provider to newest upstream release

---

app/controllers/catalog_controller.rb
app/models/oai_set.rb
app/models/solr_document.rb

Adds the missing set configuration from #2236

Configure OAI sets for new blacklight_oai_provider gem

---

.rubocop_fix_me.yml
app/jobs/reindex_model_job.rb
lib/tasks/reindex_by_model.rake

This is a cool new rake task that grabs all the URIs from Fedora keyed by their model and splits them across multiple sidekiq jobs.
This is a two-point improvement:
- First, now we grab all the Fedora objects, not just works that are already in solr. This means Collections are reindex, those weird AccessControl objects are reindexed, and anything that somehow slipped by the solr index will be indexed.
- Second, more jobs means more threads can be utilized, means a faster reindex.

Add reindex by Fedora model rake task

---

Gemfile
Gemfile.lock

Reverts osulp/Scholars-Archive#2246
Nokogiri > 1.11 requires glibc >2.17. Our current boxes do not support this, so we'll have to wait until SA@OSU is in the cluster

Revert "Bump nokogiri from 1.10.10 to 1.11.4"

---

config/initializers/grant_edit_from_members_job_hack.rb
config/initializers/revoke_edit_from_members_job_hack.rb

Fixes #1955 
The problem was when Hyrax goes to query FileSet ids to revoke/grant access to, they didn't specify the number of rows to look for, so they ended up with the default 10.

Hacks to grab all fileset ids in grant/revoke_edit_from_members jobs

---

app/jobs/replace_predicate_job.rb
app/models/concerns/scholars_archive/default_metadata.rb
lib/tasks/reindex_by_chunk.rake
lib/tasks/remove_abstract_and_title_data.rake
lib/tasks/update_conference_section_data.rake

This will update the conference section predicate to use `w3id` rather than `w2id`. After merging we will want to quickly run `rake scholars_archive:update_conference_section_data` to update all the old values on all works to the new predicate.
supersedes #2282
Fixes #1781, #1782

Update conference section predicate

---

Dockerfile
config/initializers/yabeda.rb
config/prometheus_client.yml

- enable prometheus_client gem Direct File Store via initializer
- enable yabeda-rails metrics via yabeda.rb initializer
- install py3-pip package and run `pip install s3cmd` to install `s3cmd` tool

infrastructure tweaks

---

config/initializers/honeycomb.rb

For local dev and to allow us to easily disable Honeycomb output

add a HONEYCOMB_ENABLED toggle 

---

app/views/datasets/edit_fields/_license.html.erb

Adding in a new file to override the base license file to have it populate the copyright in the box in the dataset section only.

Prepopulate the license only in Dataset

---

app/assets/stylesheets/osu.scss
app/views/hyrax/base/_workflow_actions.html.erb

Given feedback on the datetime, we formatted a way that differentiate between which comments belong under which comment.

Update timedate format based on feedback

---

app/views/datasets/edit_fields/_rights_statement.html.erb

Add in the pre-select copyright statement to display "No Copyright - United States" as a pre selected option when filling out the datasets.

Add in pre-selected Copyright

---

build/entrypoint-sidekiq.sh

removed fallthrough loop from entrypoint-sidekiq.sh
when Sidekiq crashes, rather than allowing the container to die we still have the "fallthrough loop" in `entrypoint-sidekiq.sh`. Rather than exiting, the script goes into a while loop for debugging.
this PR removes the fallback loop

allow Sidekiq workers to fail gracefully

---

app/views/datasets/edit_fields/_license.html.erb

Create a fix to the default Dataset license issue where it stuck on the same license no matter if selected a different one.

Add fix to the default CC 4.0

---

app/views/hyrax/base/_items.html.erb

Fix the bug where the button is still clickable when it is disable, and change to present if FileSets are presented there

Add in bug fix to the delete all button

---

config/analytics.yml

Add in the `Google Analytics` key to the YML file to see if this fix the `Scholars Archive` analytics.
#2442

Integrate the GA with API keys

---

app/services/scholars_archive/triple_powered_service.rb

Fixes #2492 by only selecting the labels that are either English or US-English, if the language can be determined

Filter out non-english labels if language is detectable

---

config/initializers/hacks/hyrax_file_sets_controller_hack.rb

Prevent fileset page from displaying if parent is in workflow

---

.circleci/config.yml
app/views/_ga.html.erb

Add in the code again for GA4 to SA as SQL8 mess up some of the branch

Add in GA4 to SA

---

app/jobs/reindex_chunk_job.rb
lib/tasks/reindex_by_chunk.rake

Improvement to the built in Fedora crawler, now with logging and reduced overhead. Also parallelize-able in the future if Fedora/Network can handle it
Fixes #2304

Use custom Fedora crawler in reindex by chunk job

---

app/controllers/concerns/scholars_archive/download_analytics_behavior.rb

Add in a special case to ignore some admin path visit to not be collected in the `GA4`.

Add in a filter to not collect admin visit

---

app/controllers/catalog_controller.rb
spec/models/solr_document_spec.rb

`UPDATE:`  Add in the update to fix the `config.oai` to set the `basedURL` to reflect the `https` rather than the `http`.

Update OAI config from http to https

---

app/controllers/concerns/scholars_archive/download_analytics_behavior.rb

This potentially may alleviate some of the bot traffic reported to GA4

Pass request headers through to GA4

---

app/jobs/characterize_job.rb

Check for response to #alpha_channel= when characterizing filesets

---

lib/tasks/fixity_check.rake

`UPDATE:` Change a minor in counting failed files on fixity report.

Change minor fixity report task

---

config/initializers/hacks/hyrax_file_sets_controller_hack.rb

This refactors to remove the overridden show method from FileSetsController. Its not needed if we just write a new method and prepend it in a before action.
This also prepends two methods. One being the redirect if restricted behavior and the second being the "unavailable" redirect. The first one to fire will be the redirect if restricted. If that one doesnt go through then the next one will. that should catch all the redirects for the filesets. If both fail then it'll flow naturally through the show action.

Update to clean up overridden controller

---

app/models/administrative_report_or_publication.rb
app/models/concerns/scholars_archive/default_metadata.rb
app/models/conference_proceedings_or_journal.rb
app/models/graduate_project.rb
app/models/graduate_thesis_or_dissertation.rb
app/models/honors_college_thesis.rb
app/models/technical_report.rb
app/models/undergraduate_thesis_or_project.rb
config/authorities/peerreviewed.yml
lib/tasks/update_peer_reviewed_data.rake
spec/services/scholars_archive/peerreviewed_service_spec.rb

`UDPATE:` Make an adjustment to the ontology of the `peer review` subject term and updated to a new URI predicate and other areas that uses the old ontology.

Update Peer Review Ontology

---

.circleci/config.yml
config/authorities/other_affiliation.yml

@simholt we won't be to deploy #2651 until #2549 is QA'd. I'm opening a new PR to allow us to build temporary patches based on other points of history and I'm applying your fix. We can have a temp deploy w/o #2549 until it's QA'd

Sarah's update to other_affiliation.yml

---

.rubocop_fix_me.yml
app/assets/javascripts/hyrax/autocomplete.es6
app/authorities/qa/authorities/research_organization_registry.rb
app/controllers/catalog_controller.rb
app/controllers/concerns/scholars_archive/works_controller_behavior.rb
app/models/concerns/scholars_archive/default_metadata.rb
app/models/solr_document.rb
app/presenters/concerns/scholars_archive/default_presenter_behavior.rb
app/services/scholars_archive/research_organization_registry_service.rb
app/views/records/edit_fields/_funding_body.html.erb
app/workers/fetch_failed_graph_worker.rb
app/workers/fetch_graph_worker.rb
lib/qa/authorities/geonames.rb
lib/qa/authorities/research_organization_registry.rb
lib/scholars_archive/attributes_list.rb
lib/scholars_archive/controlled_vocabularies/research_organization_registry.rb
spec/fixtures/ror.json
spec/models/solr_document_spec.rb
spec/services/scholars_archive/research_organization_registry_service_spec.rb

`FEATURE:` Add in an autocomplete search function to the new `ROR` search based into the `funding_body`.
`PROGRESS:`
`Part 1: Display`
`Part 2: CV`
`Part 3: Test`

Added in new ROR search to funding body

---

app/assets/javascripts/hyrax/autocomplete.es6
app/forms/concerns/scholars_archive/article_terms.rb
app/models/concerns/scholars_archive/finalize_nested_metadata.rb
app/views/records/edit_fields/_funding_body.html.erb

`BUG:` Add in a way to remove an extra field on `:new` or `work have blank` funding body for work on depositor form.

Remove an extra field in funding body

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/hyrax.scss
app/assets/stylesheets/osu.scss

You can override bootstrap variables in `_variables.scss` for global bootstrap changes
https://github.com/twbs/bootstrap-rubygem/blob/4.6-stable/assets/stylesheets/bootstrap/_variables.scss

Add space to override bootstrap variables

---

config/authorities/accessibility_feature.yml

`FEATURE:` Update the `accessibility_feature` to include in the value of `none` from previous work done on `accessibility_feature`.
fixes #2761

Add in 'none' to Accessibility Feature

---

app/controllers/bot_detection_controller.rb

Same fix as OregonDigital/OD2#3420

Combine challenge destination query params with an & instead of a ?
